import { createClient } from '@supabase/supabase-js';
import { createADEIDraft, getADEIDesignTypes } from './adei.js';

const URL = import.meta.env.VITE_SUPABASE_URL || 'https://nfvkdqpxexfymzuwdorx.supabase.co';
const KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.VITE_SUPABASE_ANON_KEY || 'sb_publishable_4BG89zR_2gWWWeLqqDzALw_Atx9jAJ6';
const sb = createClient(URL, KEY);
const ID='adei-studio';
const labels={SITE_PLAN:'Site Plan',FLOOR_PLAN:'Floor Plan',FACADE:'Facade',EXTERIOR:'Exterior',INTERIOR:'Interior',STRUCTURAL:'Structural',MEP:'MEP',LANDSCAPE:'Landscape',GREEN_BUILDING:'Green Building',RESILIENCE:'Resilience',BOQ_RAB:'BOQ / RAB',SCHEDULE:'Schedule'};
const esc=(v='')=>String(v).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]||c));
let context={};

function styles(){if(document.getElementById(ID+'-style'))return;const s=document.createElement('style');s.id=ID+'-style';s.textContent=`#${ID}{margin:0 0 24px;border:1px solid #2b2924;border-radius:18px;background:#0e0f11;overflow:hidden;box-shadow:0 18px 60px #0004}#${ID} .adei-head{padding:20px 22px;border-bottom:1px solid #292721;display:flex;justify-content:space-between;gap:20px;align-items:start}#${ID} h2{font:800 25px Manrope;margin:0 0 7px;color:#f3eee5}#${ID} p{margin:0;color:#8e887e;font-size:12px;line-height:1.6}#${ID} .adei-status{font-size:9px;letter-spacing:.12em;color:#b99b61;border:1px solid #4d4029;border-radius:999px;padding:6px 9px;white-space:nowrap}#${ID} .adei-body{padding:20px 22px;display:grid;grid-template-columns:1.25fr .75fr;gap:22px}#${ID} .adei-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}#${ID} label{display:grid;gap:6px;color:#aaa398;font-size:10px;font-weight:700}#${ID} .full{grid-column:1/-1}#${ID} input,#${ID} textarea,#${ID} select{width:100%;border:1px solid #36332d;border-radius:9px;background:#111214;color:#eee8dd;padding:10px;outline:none}#${ID} textarea{min-height:82px;resize:vertical}#${ID} input:focus,#${ID} textarea:focus,#${ID} select:focus{border-color:#75613d;box-shadow:0 0 0 3px #75613d18}#${ID} .types{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin-top:7px}#${ID} .type{border:1px solid #302d27;background:#121315;color:#8f897f;border-radius:8px;padding:8px;text-align:left;font-size:10px}#${ID} .type.selected{border-color:#75613d;color:#e2c17e;background:#191611}#${ID} .side{border-left:1px solid #292721;padding-left:20px}#${ID} .gate{padding:13px;border:1px solid #292721;border-radius:11px;background:#111214;margin-bottom:9px}#${ID} .gate b,#${ID} .gate span{display:block}#${ID} .gate b{font-size:11px;color:#ddd5c8}#${ID} .gate span{font-size:10px;color:#777169;margin-top:4px;line-height:1.5}#${ID} .actions{display:flex;gap:8px;margin-top:16px;flex-wrap:wrap}#${ID} button.primary{border:0;border-radius:9px;background:#c7a86a;color:#111;padding:11px 14px;font-weight:800;font-size:11px}#${ID} button.secondary{border:1px solid #38342d;border-radius:9px;background:#151618;color:#c9c0b2;padding:11px 14px;font-weight:700;font-size:11px}#${ID} .result{margin:0 22px 20px;padding:12px 14px;border-left:2px solid #6b5835;background:#121315;color:#aaa398;font-size:11px;line-height:1.6;white-space:pre-wrap}#${ID} .result.ok{color:#b7c7a7;border-color:#536343}#${ID} .result.err{color:#d9a39b;border-color:#70463f}@media(max-width:820px){#${ID} .adei-body{grid-template-columns:1fr}#${ID} .side{border-left:0;border-top:1px solid #292721;padding:18px 0 0}#${ID} .types{grid-template-columns:1fr 1fr}}@media(max-width:520px){#${ID} .adei-grid{grid-template-columns:1fr}#${ID} .types{grid-template-columns:1fr}#${ID} .adei-head{display:block}#${ID} .adei-status{display:inline-block;margin-top:12px}}`;document.head.appendChild(s)}

function mount(contextInput={}){if(document.getElementById(ID))return;context=contextInput;styles();const root=document.createElement('section');root.id=ID;root.innerHTML=`<div class="adei-head"><div><h2>AI Design & Engineering Intelligence</h2><p>Design intake ter-governance untuk architecture, engineering, BOQ/RAB, schedule, resilience, dan review Director.</p></div><span class="adei-status">BASELINE LOCKED BY DEFAULT</span></div><div class="adei-body"><div><div class="adei-grid"><label class="full">Judul studi<input name="title" maxlength="160" placeholder="Contoh: Studi Konsep Gedung Komersial ADTrans"></label><label>Sumber<select name="source"><option value="TEXT">Command / Brief</option><option value="IMAGE">Image / Photo</option><option value="SKETCH">Sketch</option><option value="PDF">PDF / Document</option><option value="CAD_BIM">CAD / BIM</option></select></label><label>Target tanggal<input name="date" type="date"></label><label class="full">Budget target<input name="budget" type="number" min="0" step="1" placeholder="Nilai indikatif, bukan approval finance"></label><label class="full">Tujuan desain<textarea name="objectives" placeholder="Tujuan, kebutuhan pengguna, target performa, prioritas...\"></textarea></label><label class="full">Kendala / constraint<textarea name="constraints" placeholder="Lahan, regulasi, biaya, waktu, material, lingkungan, akses...\"></textarea></label><label class="full">Output yang dibutuhkan<div class="types">${getADEIDesignTypes().map(t=>`<button type="button" class="type" data-type="${t}">${labels[t]||t}</button>`).join('')}</div></label></div><div class="actions"><button class="primary" data-create>Buat AI Design Intake</button><button class="secondary" data-refresh>Refresh intake</button></div></div><aside class="side"><div class="gate"><b>Professional validation</b><span>AI menghasilkan studi awal. Struktur, MEP, keselamatan, regulasi, dan dokumen profesional tetap memerlukan review ahli yang berwenang.</span></div><div class="gate"><b>Director approval</b><span>Approval diperlukan sebelum desain menjadi baseline resmi dan diteruskan ke procurement, construction, finance, atau digital twin.</span></div><div class="gate"><b>Traceability</b><span>Setiap intake menyimpan source, objectives, constraints, budget target, target date, status, dan governance.</span></div><div class="gate"><b>Current role</b><span>${esc(context.role||'STAFF')} · ${esc(context.fullName||'Authenticated user')}</span></div></aside></div><div class="result" data-result>Belum ada intake dibuat.</div>`;const target=document.querySelector('#content')||document.querySelector('main');if(target)target.prepend(root);else document.body.appendChild(root);
const selected=new Set();root.querySelectorAll('[data-type]').forEach(b=>b.addEventListener('click',()=>{const t=b.dataset.type;if(selected.has(t)){selected.delete(t);b.classList.remove('selected')}else{selected.add(t);b.classList.add('selected')}}));root.querySelector('[data-create]').addEventListener('click',async()=>{const q=s=>root.querySelector(`[name="${s}"]`)?.value||'';const out=root.querySelector('[data-result]');out.className='result';out.textContent='Menyimpan AI Design Intake…';try{const data=await createADEIDraft({title:q('title'),sourceType:q('source'),targetDate:q('date')||null,budgetTarget:q('budget')?Number(q('budget')):null,objectives:q('objectives'),constraints:q('constraints'),designTypes:[...selected]});out.className='result ok';out.textContent=`Intake ${data.id} tersimpan. Status: ${data.status}. Baseline tetap terkunci sampai governance review dan approval.`}catch(e){out.className='result err';out.textContent=`Gagal membuat intake: ${e?.message||e}`}});root.querySelector('[data-refresh]').addEventListener('click',async()=>{const out=root.querySelector('[data-result]');try{const {data,error}=await sb.from('ai_design_intakes').select('id,title,status,created_at,design_types').order('created_at',{ascending:false}).limit(8);if(error)throw error;out.className='result ok';out.textContent=(data||[]).length?data.map(x=>`${x.status} · ${x.title} · ${new Date(x.created_at).toLocaleString('id-ID')}`).join('\n'):'Belum ada design intake.'}catch(e){out.className='result err';out.textContent=`Refresh gagal: ${e?.message||e}`}})}
export function mountADEI(contextInput={}){mount(contextInput)}
