import { createClient } from '@supabase/supabase-js';
import './style.css';

const url = import.meta.env.VITE_SUPABASE_URL;
const key = import.meta.env.VITE_SUPABASE_ANON_KEY;
const sb = url && key ? createClient(url, key) : null;
const app = document.querySelector('#app');
const esc = s => String(s ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const fmt = n => new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n||0));
const num = n => new Intl.NumberFormat('id-ID',{maximumFractionDigits:0}).format(Number(n||0));

const modules=[['Executive Cockpit','⌂'],['Land Bank','▦'],['Property & Asset','◈'],['Development','◆'],['Investment','◇'],['Finance','Rp'],['Contracts & Legal','§'],['Risk & Compliance','!'],['Governance','✓'],['KPI & Alerts','◉']];
const configs={
 'Land Bank':{table:'land_assets',title:'LAND BANK',desc:'Register bidang tanah, legal status, valuation, zoning, encumbrance dan development potential.',cols:['code','name','area_m2','location','legal_status','acquisition_value'],labels:['Code','Name','Area','Location','Legal','Acquisition']},
 'Property & Asset':{table:'properties',title:'PROPERTY & ASSET',desc:'Portfolio properti dan lifecycle aset dengan kontrol ownership, status dan nilai.',cols:['code','name','property_type','status','area_m2','asking_value'],labels:['Code','Name','Type','Status','Area','Asking Value']},
 'Development':{table:'property_projects',title:'DEVELOPMENT CONTROL',desc:'Pipeline proyek, target GDV, margin, timeline dan delivery control.',cols:['code','name','status','gdv','target_margin_pct','start_date','target_end_date'],labels:['Code','Project','Status','GDV','Margin','Start','Target End']},
 'Investment':{table:'investment_cases',title:'INVESTMENT',desc:'Investment case, return metrics dan decision workflow untuk capital allocation.',cols:['id','name','irr','npv','roi','approved','created_at'],labels:['ID','Case','IRR','NPV','ROI','Approved','Created']},
 'Finance':{table:'financial_transactions',title:'FINANCE CONTROL',desc:'Transaction ledger, project cash movement dan reference-based financial control.',cols:['transaction_date','account_code','description','debit','credit','reference_no'],labels:['Date','Account','Description','Debit','Credit','Reference']},
 'Contracts & Legal':{table:'contracts',title:'CONTRACT & LEGAL',desc:'Contract register, counterparty, value, dates dan document control.',cols:['contract_no','title','counterparty','start_date','end_date','value','status'],labels:['Contract No','Title','Counterparty','Start','End','Value','Status']},
 'Risk & Compliance':{table:'project_risks',title:'RISK & COMPLIANCE',desc:'Risk register, probability, impact, mitigation dan ownership untuk early intervention.',cols:['title','level','probability','impact','due_date','closed_at'],labels:['Risk','Level','Probability','Impact','Due Date','Closed']},
 'Governance':{table:'approvals',title:'GOVERNANCE',desc:'Approval matrix, segregation of duties, decisions dan audit trail.',cols:['id','entity_type','status','requested_at','decided_at'],labels:['ID','Entity','Status','Requested','Decided']},
 'KPI & Alerts':{table:'management_alerts',title:'KPI & MANAGEMENT ALERTS',desc:'Early-warning signals dan management alerts untuk menjaga target tetap terkendali.',cols:['title','severity','status','created_at','resolved_at'],labels:['Alert','Severity','Status','Created','Resolved']}
};

function publicSite(){
 document.title='ADTrans RealIndo — Property, Investment & Development';
 app.innerHTML=`<div class="public"><header class="pubnav"><div class="brand"><span>AD</span><div><b>ADTRANS</b><small>REALINDO</small></div></div><nav><a href="#home">Home</a><a href="#about">About</a><a href="#projects">Projects</a><a href="#investment">Investment</a><a href="#contact">Contact</a></nav><a class="navcta" href="#imcs">IMCS Login →</a></header><main>
 <section id="home" class="pubhero"><div class="hero-copy"><p class="eyebrow">ADTRANS REALINDO</p><h1>Building value.<br><em>Governing with evidence.</em></h1><p>Platform pengembangan properti dan investasi yang menghubungkan land bank, development, capital, governance dan delivery dalam satu operating model.</p><div class="hero-actions"><a class="primary" href="#projects">Explore portfolio</a><a class="secondary" href="#contact">Partner with us</a></div></div><div class="hero-orbit"><div class="orbit-core">REAL<br><span>INDO</span></div><i>LAND</i><i>CAPITAL</i><i>DEVELOPMENT</i><i>GOVERNANCE</i></div></section>
 <section id="about" class="pubsection"><div class="section-tag">01 · OUR PLATFORM</div><div class="split"><div><h2>From opportunity<br>to <em>real value.</em></h2></div><div><p>ADTrans RealIndo dirancang sebagai platform bisnis properti yang menempatkan kualitas aset, disiplin investasi, transparansi proses dan pengendalian risiko sebagai satu kesatuan.</p><div class="feature-grid"><article><b>Land Intelligence</b><span>Data tanah, legal, valuation dan potential development.</span></article><article><b>Development Control</b><span>Pipeline, cost, schedule, risk dan delivery.</span></article><article><b>Investment Discipline</b><span>Investment case, return metrics dan approval workflow.</span></article><article><b>Governance by Design</b><span>Evidence, segregation, audit trail dan accountability.</span></article></div></div></div></section>
 <section id="projects" class="pubsection dark"><div class="section-tag">02 · PROJECTS</div><h2>Portfolio built on<br><em>validated opportunities.</em></h2><div class="project-grid"><article><span>LAND BANK</span><h3>Strategic Land Assets</h3><p>Inventaris dan pengembangan aset tanah berdasarkan legal, lokasi, valuation dan feasibility.</p></article><article><span>PROPERTY DEVELOPMENT</span><h3>Residential & Mixed Use</h3><p>Pipeline proyek dikelola dari feasibility sampai delivery dengan kontrol biaya dan risiko.</p></article><article><span>INVESTMENT</span><h3>Capital Partnerships</h3><p>Kerangka kerja untuk investor dan partner dengan data room serta governance yang terukur.</p></article></div><div class="data-note">Project-specific public data will be published only after internal validation and authorization. No unverified legacy data is displayed.</div></section>
 <section id="investment" class="pubsection"><div class="section-tag">03 · INVESTMENT</div><div class="split"><div><h2>Capital deserves<br><em>clarity.</em></h2></div><div class="investment-panel"><div><b>01</b><span>Validated opportunity</span></div><div><b>02</b><span>Financial case & assumptions</span></div><div><b>03</b><span>Due diligence & risk</span></div><div><b>04</b><span>Approval & execution control</span></div></div></div></section>
 <section id="contact" class="pubsection contact"><div><div class="section-tag">04 · CONNECT</div><h2>Let's build the<br><em>next asset.</em></h2><p>Untuk partnership, project development, investment atau property enquiries, hubungi tim ADTrans RealIndo.</p></div><a class="primary" href="mailto:info@adtransrealindo.com">Start a conversation →</a></section></main><footer><span>© ${new Date().getFullYear()} ADTrans RealIndo</span><span>CONTROL • GOVERN • GROW</span></footer></div>`;
}

function shell(){
 document.title='ADTrans RealIndo — IMCS';
 app.innerHTML=`<div class="shell"><aside><div class="brand"><span>AD</span><div><b>ADTRANS</b><small>REALINDO · IMCS</small></div></div><nav>${modules.map(([x,i],n)=>`<button class="nav ${n===0?'active':''}" data-page="${x}"><span>${i}</span>${x}</button>`).join('')}</nav><div class="sidefoot"><b>CONTROL • GOVERN • GROW</b><br><span>Production foundation · v1.1</span></div></aside><main><header><div><div class="eyebrow">INTEGRATED MANAGEMENT CONTROL SYSTEM</div><h1 id="title">Executive Cockpit</h1></div><div class="top-actions"><span class="status"><i></i><span id="connection">${sb?'SUPABASE READY':'CONFIG REQUIRED'}</span></span><button id="logout" class="ghost">Sign out</button><button id="refresh" class="ghost">↻ Refresh</button></div></header><section id="content"></section></main></div>`;
 const navs=document.querySelectorAll('.nav'); navs.forEach(b=>b.onclick=()=>{navs.forEach(x=>x.classList.remove('active'));b.classList.add('active');page(b.dataset.page);});
 document.querySelector('#refresh').onclick=()=>page(document.querySelector('.nav.active')?.dataset.page||'Executive Cockpit');
 document.querySelector('#logout').onclick=async()=>{if(sb) await sb.auth.signOut(); location.hash='#home'; publicSite();};
 dashboard();
}
function login(){
 document.title='ADTrans RealIndo — Secure IMCS';
 app.innerHTML=`<div class="login-page"><div class="login-card"><div class="brand"><span>AD</span><div><b>ADTRANS</b><small>REALINDO · IMCS</small></div></div><p class="eyebrow">SECURE MANAGEMENT ACCESS</p><h1>Executive control,<br><em>authorized only.</em></h1><p class="muted">IMCS menggunakan Supabase Auth dan organization-scoped RLS. Data internal tidak dibuka melalui website publik.</p><form id="login"><label>Email<input type="email" id="email" required autocomplete="email"></label><label>Password<input type="password" id="password" required autocomplete="current-password"></label><button class="primary" type="submit">Sign in →</button><div id="loginmsg"></div></form><a class="backlink" href="#home">← Back to ADTrans RealIndo</a></div></div>`;
 document.querySelector('#login').onsubmit=async e=>{e.preventDefault();const msg=document.querySelector('#loginmsg');if(!sb){msg.textContent='Supabase environment belum dikonfigurasi.';return;}msg.textContent='Authenticating…';const {error}=await sb.auth.signInWithPassword({email:email.value,password:password.value});if(error){msg.textContent=error.message;return;}location.hash='#imcs';imcs();};
}
async function imcs(){if(!sb){login();return;}const {data}=await sb.auth.getSession();if(!data.session){login();return;}shell();}
async function query(table,columns='*',limit=25){if(!sb)return {data:[],error:null};return sb.from(table).select(columns).limit(limit);}
function loading(){document.querySelector('#content').innerHTML='<div class="loading"><span></span><span></span><span></span> Loading management data…</div>';}
function empty(t,d){return `<div class="empty"><div class="emptyicon">◇</div><h3>${t}</h3><p>${d}</p></div>`;}
async function dashboard(){loading();if(!sb){renderDashboard({landArea:0,gdv:0,cost:0,risks:0,projects:0});return;}try{const [l,p,r,c]=await Promise.all([query('land_assets','area_m2',1000),query('property_projects','gdv',1000),sb.from('project_risks').select('id').is('closed_at',null).limit(1000),query('project_costs','budget,actual',1000)]);const landArea=(l.data||[]).reduce((a,x)=>a+Number(x.area_m2||0),0);const gdv=(p.data||[]).reduce((a,x)=>a+Number(x.gdv||0),0);const budget=(c.data||[]).reduce((a,x)=>a+Number(x.budget||0),0);const actual=(c.data||[]).reduce((a,x)=>a+Number(x.actual||0),0);renderDashboard({landArea,gdv,cost:budget?Math.round(actual/budget*100):0,risks:(r.data||[]).length,projects:(p.data||[]).length});}catch(e){renderDashboard({landArea:0,gdv:0,cost:0,risks:0,projects:0,error:e.message});}}
function renderDashboard(m){const c=document.querySelector('#content');c.innerHTML=`<div class="hero"><div><p class="eyebrow">ADTRANS REALINDO</p><h2>Control the portfolio.<br><em>Decide with evidence.</em></h2><p class="muted">Satu control plane untuk tanah, proyek properti, investasi, keuangan, risiko, kontrak dan tata kelola—dibangun untuk keputusan manajemen yang dapat diaudit.</p><div class="hero-actions"><button class="primary" data-jump="Land Bank">Open portfolio →</button><button class="secondary" data-jump="Risk & Compliance">Review risks</button></div></div><div class="signal"><span>CONTROL STATUS</span><strong>OPERATIONAL</strong><small>Live connection ke Supabase. Data legacy tidak dipromosikan tanpa validasi.</small><div class="signalline"><i></i><i></i><i></i><i></i><i></i></div></div></div><div class="cards"><article><span>LAND BANK</span><b>${num(m.landArea)} <small>m²</small></b><label>Controlled land area</label></article><article><span>PROJECT GDV</span><b>${fmt(m.gdv)}</b><label>Gross development value</label></article><article><span>COST EXECUTION</span><b>${m.cost}%</b><label>Actual against budget</label></article><article><span>OPEN RISKS</span><b>${num(m.risks)}</b><label>Unclosed risk register</label></article></div><div class="grid"><div class="panel"><div class="panelhead"><div><h3>Management Control Plane</h3><p>Core operating domains</p></div><span>LIVE VIEW</span></div><div class="domain-grid">${modules.slice(1).map(([n,ic])=>`<button data-jump="${n}"><span>${ic}</span><div><b>${n}</b><small>Open module</small></div><strong>→</strong></button>`).join('')}</div></div><div class="panel"><div class="panelhead"><div><h3>Control Principles</h3><p>Governance by design</p></div></div><ul class="principles"><li>Evidence before migration</li><li>RLS + organization isolation</li><li>Approval & audit trail</li><li>No fabricated business data</li><li>Decision-ready management view</li></ul></div></div>`;bindJumps();}
async function modulePage(name){const cfg=configs[name];if(!cfg)return dashboard();loading();let rows=[],error=null;if(sb){const res=await query(cfg.table,cfg.cols.join(','),25);rows=res.data||[];error=res.error?.message;}const body=rows.length?`<div class="tablewrap"><table><thead><tr>${cfg.labels.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${cfg.cols.map((col,i)=>`<td>${cell(col,r[col])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:empty('No production records yet',sb?(error||'Module siap. Data akan muncul setelah data terotorisasi dimasukkan.'):'Connect Supabase to display production records.');document.querySelector('#content').innerHTML=`<div class="module-head"><div><p class="eyebrow">ADTRANS REALINDO IMCS</p><h2>${cfg.title}</h2><p class="muted">${cfg.desc}</p></div><div class="module-tools"><span class="count">${rows.length} records</span><button class="primary" id="reload-module">↻ Refresh</button></div></div><div class="module-note"><span>●</span><div><b>CONTROLLED DATA VIEW</b><small>Organization-scoped access is enforced by Supabase RLS. Legacy data remains outside production until reconciliation is approved.</small></div></div>${body}`;document.querySelector('#reload-module')?.addEventListener('click',()=>modulePage(name));}
function cell(c,v){if(v==null||v==='')return '<span class="dash">—</span>';if(['value','gdv','investment_amount','debit','credit','acquisition_value','npv'].includes(c))return `<strong>${fmt(v)}</strong>`;if(['area_m2'].includes(c))return `${num(v)} m²`;if(['target_margin_pct','irr','roi','probability','impact'].includes(c))return `${v}%`;if(c.endsWith('_at')||c.endsWith('_date'))return new Date(v).toLocaleDateString('id-ID');if(['status','level','severity'].includes(c))return `<span class="pill">${esc(v)}</span>`;if(typeof v==='boolean')return v?'YES':'NO';return esc(v);}
function page(n){document.querySelector('#title').textContent=n;n==='Executive Cockpit'?dashboard():modulePage(n);}
function bindJumps(){document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>{const n=b.dataset.jump;document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===n));page(n);});}
function router(){const h=location.hash.toLowerCase();if(h.startsWith('#imcs'))imcs();else publicSite();}
window.addEventListener('hashchange',router);router();
