import { createClient } from '@supabase/supabase-js';
import './style.css';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;
const sb = SUPABASE_URL && SUPABASE_KEY ? createClient(SUPABASE_URL, SUPABASE_KEY) : null;
const app = document.querySelector('#app');

const esc = (v) => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const money = (v) => new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(v||0));
const number = (v) => new Intl.NumberFormat('id-ID',{maximumFractionDigits:2}).format(Number(v||0));
const date = (v) => v ? new Intl.DateTimeFormat('id-ID',{dateStyle:'medium'}).format(new Date(v)) : '—';

const modules = [
  ['Executive Cockpit','⌂'],['Land Bank','▦'],['Property & Asset','◈'],['Development','◆'],
  ['Investment','◇'],['Finance','Rp'],['Contracts & Legal','§'],['Risk & Compliance','!'],
  ['Governance','✓'],['KPI & Alerts','◉']
];

const configs = {
  'Land Bank': {table:'land_assets',title:'LAND BANK',singular:'Land Asset',desc:'Register bidang tanah, legal status, valuation, zoning, encumbrance dan development potential.',search:['code','name','location','legal_status'],cols:['code','name','area_m2','location','legal_status','acquisition_value'],labels:['Code','Name','Area','Location','Legal','Acquisition'],fields:[['code','Code','text',true],['name','Name','text',true],['location','Location','text',false],['area_m2','Area (m²)','number',false],['acquisition_value','Acquisition Value','number',false],['current_value','Current Value','number',false],['legal_status','Legal Status','text',false],['zoning','Zoning','text',false],['encumbrance','Encumbrance','text',false],['development_potential','Development Potential','textarea',false]],fmt:{area_m2:'number',acquisition_value:'money'}},
  'Property & Asset': {table:'properties',title:'PROPERTY & ASSET',singular:'Property',desc:'Portfolio properti dan lifecycle aset dengan kontrol ownership, status dan nilai.',search:['code','name','property_type','status'],cols:['code','name','property_type','status','area_m2','asking_value'],labels:['Code','Name','Type','Status','Area','Asking Value'],fields:[['code','Code','text',true],['name','Name','text',true],['property_type','Property Type','text',false],['status','Status','text',false],['area_m2','Area (m²)','number',false],['asking_value','Asking Value','number',false]],fmt:{area_m2:'number',asking_value:'money'}},
  'Development': {table:'property_projects',title:'DEVELOPMENT CONTROL',singular:'Project',desc:'Pipeline proyek, target GDV, margin, timeline dan delivery control.',search:['code','name','status'],cols:['code','name','status','gdv','target_margin_pct','start_date','target_end_date'],labels:['Code','Project','Status','GDV','Margin','Start','Target End'],fields:[['code','Project Code','text',true],['name','Project Name','text',true],['status','Status','select',false,['PIPELINE','PLANNING','ACTIVE','ON_HOLD','COMPLETED','CANCELLED']],['gdv','GDV','number',false],['target_margin_pct','Target Margin (%)','number',false],['start_date','Start Date','date',false],['target_end_date','Target End Date','date',false]],fmt:{gdv:'money',target_margin_pct:'pct',start_date:'date',target_end_date:'date'}},
  'Investment': {table:'investment_cases',title:'INVESTMENT',singular:'Investment Case',desc:'Investment case, return metrics dan decision workflow untuk capital allocation.',search:['name'],cols:['name','irr','npv','roi','approved','created_at'],labels:['Case','IRR','NPV','ROI','Approved','Created'],fields:[['name','Case Name','text',true],['assumptions','Assumptions (JSON)','textarea',false],['irr','IRR (%)','number',false],['npv','NPV','number',false],['roi','ROI (%)','number',false],['approved','Approved','checkbox',false]],fmt:{irr:'pct',npv:'money',roi:'pct',created_at:'date'}},
  'Finance': {table:'financial_transactions',title:'FINANCE CONTROL',singular:'Transaction',desc:'Transaction ledger, project cash movement dan reference-based financial control.',search:['account_code','description','reference_no'],cols:['transaction_date','account_code','description','debit','credit','reference_no'],labels:['Date','Account','Description','Debit','Credit','Reference'],fields:[['transaction_date','Transaction Date','date',true],['account_code','Account Code','text',true],['description','Description','textarea',false],['debit','Debit','number',false],['credit','Credit','number',false],['reference_no','Reference No.','text',false]],fmt:{transaction_date:'date',debit:'money',credit:'money'}},
  'Contracts & Legal': {table:'contracts',title:'CONTRACT & LEGAL',singular:'Contract',desc:'Contract register, counterparty, value, dates dan document control.',search:['contract_no','title','counterparty','status'],cols:['contract_no','title','counterparty','start_date','end_date','value','status'],labels:['Contract No','Title','Counterparty','Start','End','Value','Status'],fields:[['contract_no','Contract No.','text',true],['title','Title','text',true],['counterparty','Counterparty','text',false],['start_date','Start Date','date',false],['end_date','End Date','date',false],['value','Contract Value','number',false],['status','Status','text',false],['document_path','Document Path','text',false]],fmt:{start_date:'date',end_date:'date',value:'money'}},
  'Risk & Compliance': {table:'project_risks',title:'RISK & COMPLIANCE',singular:'Risk',desc:'Risk register, probability, impact, mitigation dan ownership untuk early intervention.',search:['title','level','description','mitigation'],cols:['title','level','probability','impact','due_date','closed_at'],labels:['Risk','Level','Probability','Impact','Due Date','Closed'],fields:[['title','Risk Title','text',true],['description','Description','textarea',false],['level','Level','select',false,['LOW','MEDIUM','HIGH','CRITICAL']],['probability','Probability (%)','number',false],['impact','Impact (%)','number',false],['mitigation','Mitigation','textarea',false],['due_date','Due Date','date',false]],fmt:{probability:'pct',impact:'pct',due_date:'date',closed_at:'date'}},
  'Governance': {table:'approvals',title:'GOVERNANCE',singular:'Approval',desc:'Approval matrix, segregation of duties, decisions dan audit trail.',search:['entity_type','status'],cols:['id','entity_type','status','requested_at','decided_at'],labels:['ID','Entity','Status','Requested','Decided'],fields:[['entity_type','Entity Type','text',true],['entity_id','Entity ID (UUID)','text',true],['status','Status','select',false,['DRAFT','PENDING','APPROVED','REJECTED','CANCELLED']],['decision_note','Decision Note','textarea',false]],fmt:{requested_at:'date',decided_at:'date'}},
  'KPI & Alerts': {table:'management_alerts',title:'KPI & MANAGEMENT ALERTS',singular:'Management Alert',desc:'Early-warning signals dan management alerts untuk menjaga target tetap terkendali.',search:['title','severity','rule_code','status'],cols:['title','severity','status','created_at','resolved_at'],labels:['Alert','Severity','Status','Created','Resolved'],fields:[['rule_code','Rule Code','text',true],['title','Alert Title','text',true],['message','Message','textarea',true],['severity','Severity','select',true,['LOW','MEDIUM','HIGH','CRITICAL']],['status','Status','select',false,['OPEN','ACKNOWLEDGED','RESOLVED']]],fmt:{created_at:'date',resolved_at:'date'}}
};

let state = { profile:null, page:'Executive Cockpit', rows:[], search:'' };

function publicSite(){
  document.title='ADTrans RealIndo — Property, Investment & Development';
  app.innerHTML=`<div class="public"><header class="pubnav"><a class="brand" href="#home"><span>AD</span><div><b>ADTRANS</b><small>REALINDO</small></div></a><nav><a href="#home">Home</a><a href="#about">About</a><a href="#projects">Projects</a><a href="#investment">Investment</a><a href="#contact">Contact</a></nav><a class="navcta" href="#imcs">IMCS Login →</a></header><main>
  <section id="home" class="pubhero"><div class="hero-copy"><p class="eyebrow">ADTRANS REALINDO</p><h1>Building value.<br><em>Governing with evidence.</em></h1><p>Platform pengembangan properti dan investasi yang menghubungkan land bank, development, capital, governance dan delivery dalam satu operating model.</p><div class="hero-actions"><a class="primary" href="#projects">Explore portfolio</a><a class="secondary" href="#contact">Partner with us</a></div></div><div class="hero-orbit"><div class="orbit-core">REAL<br><span>INDO</span></div><i>LAND</i><i>CAPITAL</i><i>DEVELOPMENT</i><i>GOVERNANCE</i></div></section>
  <section id="about" class="pubsection"><div class="section-tag">01 · OUR PLATFORM</div><div class="split"><div><h2>From opportunity<br>to <em>real value.</em></h2></div><div><p>ADTrans RealIndo dirancang sebagai platform bisnis properti yang menempatkan kualitas aset, disiplin investasi, transparansi proses dan pengendalian risiko sebagai satu kesatuan.</p><div class="feature-grid"><article><b>Land Intelligence</b><span>Data tanah, legal, valuation dan development potential.</span></article><article><b>Development Control</b><span>Pipeline, cost, schedule, risk dan delivery.</span></article><article><b>Investment Discipline</b><span>Investment case, return metrics dan approval workflow.</span></article><article><b>Governance by Design</b><span>Evidence, segregation, audit trail dan accountability.</span></article></div></div></div></section>
  <section id="projects" class="pubsection dark"><div class="section-tag">02 · PROJECTS</div><h2>Portfolio built on<br><em>validated opportunities.</em></h2><div class="project-grid"><article><span>LAND BANK</span><h3>Strategic Land Assets</h3><p>Inventaris dan pengembangan aset tanah berdasarkan legal, lokasi, valuation dan feasibility.</p></article><article><span>PROPERTY DEVELOPMENT</span><h3>Residential & Mixed Use</h3><p>Pipeline proyek dikelola dari feasibility sampai delivery dengan kontrol biaya dan risiko.</p></article><article><span>INVESTMENT</span><h3>Capital Partnerships</h3><p>Kerangka kerja untuk investor dan partner dengan data room serta governance yang terukur.</p></article></div><div class="data-note">Project-specific public data hanya ditampilkan setelah internal validation dan authorization.</div></section>
  <section id="investment" class="pubsection"><div class="section-tag">03 · INVESTMENT</div><div class="split"><div><h2>Capital deserves<br><em>clarity.</em></h2></div><div class="investment-panel"><div><b>01</b><span>Validated opportunity</span></div><div><b>02</b><span>Financial case & assumptions</span></div><div><b>03</b><span>Due diligence & risk</span></div><div><b>04</b><span>Approval & execution control</span></div></div></div></section>
  <section id="contact" class="pubsection contact"><div><div class="section-tag">04 · CONNECT</div><h2>Let's build the<br><em>next asset.</em></h2><p>Untuk partnership, project development, investment atau property enquiries, hubungi tim ADTrans RealIndo.</p></div><a class="primary" href="mailto:info@adtransrealindo.com">Start a conversation →</a></section></main><footer><span>© ${new Date().getFullYear()} ADTrans RealIndo</span><span>CONTROL • GOVERN • GROW</span></footer></div>`;
}

function login(){
  document.title='ADTrans RealIndo — Secure IMCS';
  app.innerHTML=`<div class="login-page"><div class="login-card"><a class="brand" href="#home"><span>AD</span><div><b>ADTRANS</b><small>REALINDO · IMCS</small></div></a><p class="eyebrow">SECURE MANAGEMENT ACCESS</p><h1>Executive control,<br><em>authorized only.</em></h1><p class="muted">IMCS menggunakan Supabase Auth dan organization-scoped RLS. Data internal tidak dibuka melalui website publik.</p><form id="login-form"><label>Email<input id="email" type="email" autocomplete="email" required></label><label>Password<input id="password" type="password" autocomplete="current-password" required></label><button class="primary full" type="submit">Sign in →</button><div id="login-msg" class="form-msg"></div></form><a class="backlink" href="#home">← Back to ADTrans RealIndo</a></div></div>`;
  document.querySelector('#login-form').onsubmit=async(e)=>{e.preventDefault();const msg=document.querySelector('#login-msg');msg.textContent='Authenticating…';if(!sb){msg.textContent='Supabase environment belum dikonfigurasi.';return;}const {error}=await sb.auth.signInWithPassword({email:document.querySelector('#email').value,password:document.querySelector('#password').value});if(error){msg.textContent=error.message;return;}location.hash='#imcs';};
}

async function loadProfile(){
  if(!sb)return null;const {data:{user}}=await sb.auth.getUser();if(!user)return null;const {data,error}=await sb.from('profiles').select('id,organization_id,full_name,role,active').eq('id',user.id).maybeSingle();if(error)throw error;if(!data||!data.active)throw new Error('User profile tidak aktif atau belum terdaftar pada organisasi.');return data;
}

function shell(){
  document.title='ADTrans RealIndo — IMCS';const initials=(state.profile?.full_name||'AD').split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase();
  app.innerHTML=`<div class="shell"><aside><a class="brand" href="#imcs"><span>AD</span><div><b>ADTRANS</b><small>REALINDO · IMCS</small></div></a><nav>${modules.map(([name,icon],i)=>`<button class="nav ${i===0?'active':''}" data-page="${esc(name)}"><span>${icon}</span>${esc(name)}</button>`).join('')}</nav><div class="sidefoot"><b>CONTROL • GOVERN • GROW</b><br><span>Production · v2.0</span></div></aside><main><header><div><div class="eyebrow">INTEGRATED MANAGEMENT CONTROL SYSTEM</div><h1 id="page-title">Executive Cockpit</h1></div><div class="top-actions"><span class="profile-chip"><i>${esc(initials)}</i><span>${esc(state.profile?.full_name||'User')} · ${esc(state.profile?.role||'')}</span></span><button id="logout" class="ghost">Sign out</button><button id="refresh" class="ghost">↻ Refresh</button></div></header><section id="content"></section></main></div>`;
  document.querySelectorAll('.nav').forEach(btn=>btn.onclick=()=>navigate(btn.dataset.page));document.querySelector('#refresh').onclick=()=>renderPage(state.page);document.querySelector('#logout').onclick=async()=>{if(sb)await sb.auth.signOut();location.hash='#home';};renderPage('Executive Cockpit');
}
async function navigate(name){state.page=name;state.search='';document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.page===name));document.querySelector('#page-title').textContent=name;await renderPage(name);}
async function getRows(cfg){let q=sb.from(cfg.table).select(cfg.cols.join(',')).limit(100);if(['financial_transactions'].includes(cfg.table))q=q.order('transaction_date',{ascending:false});else if(cfg.cols.includes('created_at'))q=q.order('created_at',{ascending:false});const {data,error}=await q;if(error)throw error;return data||[];}
function cell(cfg,col,val){if(val===null||val===undefined||val==='')return '<span class="muted">—</span>';const type=cfg.fmt?.[col];if(type==='money')return esc(money(val));if(type==='number')return esc(number(val));if(type==='pct')return `${esc(number(val))}%`;if(type==='date')return esc(date(val));if(typeof val==='boolean')return `<span class="badge ${val?'ok':'muted-badge'}">${val?'YES':'NO'}</span>`;if(['level','severity','status'].includes(col))return `<span class="badge ${String(val).toLowerCase()}">${esc(val)}</span>`;return esc(val);}
function canWrite(){return ['SUPER_ADMIN','DIRECTOR','COMMISSIONER','EXECUTIVE','DEPARTMENT_HEAD','MANAGER'].includes(state.profile?.role);}
async function renderPage(name){const content=document.querySelector('#content');if(!content)return;if(name==='Executive Cockpit'){await dashboard();return;}const cfg=configs[name];if(!cfg){content.innerHTML=empty('Module unavailable','Konfigurasi modul tidak ditemukan.');return;}content.innerHTML=`<div class="loading"><span></span><span></span><span></span> Loading ${esc(name)}…</div>`;try{state.rows=await getRows(cfg);renderModule(cfg);}catch(e){content.innerHTML=empty('Unable to load data',e.message);}}
async function dashboard(){const c=document.querySelector('#content');if(!c)return;c.innerHTML='<div class="loading"><span></span><span></span><span></span> Loading management data…</div>';if(!sb){renderDashboard({landArea:0,gdv:0,budget:0,actual:0,risks:0,projects:0,alerts:0});return;}try{const [land,projects,costs,risks,alerts]=await Promise.all([sb.from('land_assets').select('area_m2').limit(1000),sb.from('property_projects').select('gdv').limit(1000),sb.from('project_costs').select('budget,actual').limit(2000),sb.from('project_risks').select('id').is('closed_at',null).limit(1000),sb.from('management_alerts').select('id').eq('status','OPEN').limit(1000)]);[land,projects,costs,risks,alerts].forEach(x=>{if(x.error)throw x.error;});const sum=(rows,k)=>rows.reduce((a,x)=>a+Number(x[k]||0),0);renderDashboard({landArea:sum(land.data||[],'area_m2'),gdv:sum(projects.data||[],'gdv'),budget:sum(costs.data||[],'budget'),actual:sum(costs.data||[],'actual'),risks:(risks.data||[]).length,projects:(projects.data||[]).length,alerts:(alerts.data||[]).length});}catch(e){renderDashboard({landArea:0,gdv:0,budget:0,actual:0,risks:0,projects:0,alerts:0,error:e.message});}}
function renderDashboard(m){const execution=m.budget?Math.round(m.actual/m.budget*100):0;document.querySelector('#content').innerHTML=`<div class="hero"><div><p class="eyebrow">ADTRANS REALINDO</p><h2>Control the portfolio.<br><em>Decide with evidence.</em></h2><p class="muted">Satu control plane untuk tanah, proyek properti, investasi, keuangan, risiko, kontrak dan tata kelola—dibangun untuk keputusan manajemen yang dapat diaudit.</p><div class="hero-actions"><button class="primary" data-jump="Land Bank">Open portfolio →</button><button class="secondary" data-jump="Risk & Compliance">Review risks</button></div></div><div class="signal"><span>CONTROL STATUS</span><strong>OPERATIONAL</strong><small>Live connection ke Supabase. Organization isolation aktif.</small><div class="signalline"><i></i><i></i><i></i><i></i><i></i></div></div></div><div class="cards"><article><span>LAND BANK</span><b>${number(m.landArea)} <small>m²</small></b><label>Controlled land area</label></article><article><span>PROJECT GDV</span><b>${money(m.gdv)}</b><label>Gross development value</label></article><article><span>COST EXECUTION</span><b>${execution}%</b><label>Actual against budget</label></article><article><span>OPEN RISKS</span><b>${number(m.risks)}</b><label>Unclosed risk register</label></article><article><span>OPEN ALERTS</span><b>${number(m.alerts)}</b><label>Management alerts</label></article></div><div class="grid"><div class="panel"><div class="panelhead"><div><h3>Management Control Plane</h3><p>Core operating domains</p></div><span>LIVE VIEW</span></div><div class="domain-grid">${modules.slice(1).map(([n,ic])=>`<button data-jump="${esc(n)}"><span>${ic}</span><div><b>${esc(n)}</b><small>Open module</small></div><strong>→</strong></button>`).join('')}</div></div><div class="panel"><div class="panelhead"><div><h3>Control Principles</h3><p>Governance by design</p></div></div><ul class="principles"><li>Evidence before migration</li><li>RLS + organization isolation</li><li>Role-aware write control</li><li>Approval & audit trail</li><li>No fabricated business data</li></ul></div></div>`;bindJumps();}
function empty(title,desc){return `<div class="empty"><div class="emptyicon">◇</div><h3>${esc(title)}</h3><p>${esc(desc||'')}</p></div>`;}
function renderModule(cfg){const can=canWrite();const filtered=state.rows.filter(r=>!state.search||cfg.search.some(k=>String(r[k]??'').toLowerCase().includes(state.search.toLowerCase())));const rows=filtered.map(r=>`<tr><td><button class="row-link" data-id="${esc(r.id)}">${esc(r[cfg.cols[0]]??r.id??'Open')}</button></td>${cfg.cols.slice(1).map(col=>`<td>${cell(cfg,col,r[col])}</td>`).join('')}<td class="row-actions"><button class="icon-btn edit" data-id="${esc(r.id)}" title="Edit">✎</button><button class="icon-btn danger delete" data-id="${esc(r.id)}" title="Delete">×</button></td></tr>`).join('');document.querySelector('#content').innerHTML=`<div class="module-head"><div><p class="eyebrow">ADTRANS REALINDO IMCS</p><h2>${esc(cfg.title)}</h2><p class="muted">${esc(cfg.desc)}</p></div><div class="module-tools"><span class="count">${filtered.length} records</span>${can?`<button class="primary" id="add-record">＋ New ${esc(cfg.singular)}</button>`:''}</div></div><div class="toolbar"><label class="search">⌕<input id="module-search" placeholder="Search ${esc(cfg.singular)}…" value="${esc(state.search)}"></label><button class="ghost" id="export-csv">Export CSV</button></div><div class="module-note"><span>●</span><div><b>CONTROLLED DATA VIEW</b><small>Organization-scoped access. Changes are auditable. ${can?'Write access enabled for your role.':'Read-only access for your role.'}</small></div></div><div class="tablewrap"><table><thead><tr><th>${esc(cfg.labels[0])}</th>${cfg.labels.slice(1).map(x=>`<th>${esc(x)}</th>`).join('')}<th>Actions</th></tr></thead><tbody>${rows||`<tr><td colspan="${cfg.labels.length+1}">${empty('No records','Belum ada data terotorisasi pada modul ini.')}</td></tr>`}</tbody></table></div>`;document.querySelector('#module-search').oninput=e=>{state.search=e.target.value;renderModule(cfg);};document.querySelector('#export-csv').onclick=()=>exportCsv(cfg,filtered);if(can){document.querySelector('#add-record').onclick=()=>openForm(cfg);document.querySelectorAll('.edit').forEach(b=>b.onclick=()=>openForm(cfg,state.rows.find(r=>r.id===b.dataset.id)));document.querySelectorAll('.delete').forEach(b=>b.onclick=()=>removeRecord(cfg,b.dataset.id));}document.querySelectorAll('.row-link').forEach(b=>b.onclick=()=>openForm(cfg,state.rows.find(r=>r.id===b.dataset.id),true));}
function bindJumps(){document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>navigate(b.dataset.jump));}
function inputFor([name,label,type,required,options],value){const v=value??'';if(type==='textarea')return `<label class="field full">${esc(label)}<textarea name="${esc(name)}" ${required?'required':''}>${esc(typeof v==='object'?JSON.stringify(v):v)}</textarea></label>`;if(type==='checkbox')return `<label class="check field full"><input type="checkbox" name="${esc(name)}" ${v?'checked':''}><span>${esc(label)}</span></label>`;if(type==='select')return `<label class="field">${esc(label)}<select name="${esc(name)}" ${required?'required':''}><option value="">— Select —</option>${options.map(o=>`<option value="${esc(o)}" ${v===o?'selected':''}>${esc(o)}</option>`).join('')}</select></label>`;return `<label class="field">${esc(label)}<input name="${esc(name)}" type="${type}" value="${esc(v)}" ${required?'required':''}></label>`;}
function openForm(cfg,row=null,readonly=false){const isEdit=!!row;const locked=readonly||!canWrite();const fields=cfg.fields.map(f=>inputFor(f,row?.[f[0]])).join('');const overlay=document.createElement('div');overlay.className='modal-backdrop';overlay.innerHTML=`<div class="modal"><div class="modal-head"><div><p class="eyebrow">${isEdit?'RECORD DETAIL':'NEW RECORD'}</p><h3>${isEdit?'Edit':'Create'} ${esc(cfg.singular)}</h3></div><button class="close">×</button></div><form id="record-form" class="form-grid">${fields}<div class="modal-actions"><button type="button" class="secondary close">Cancel</button>${locked?'':`<button class="primary" type="submit">${isEdit?'Save changes':'Create record'}</button>`}</div><div id="form-msg" class="form-msg"></div></form></div>`;document.body.appendChild(overlay);overlay.querySelectorAll('.close').forEach(x=>x.onclick=()=>overlay.remove());if(locked)overlay.querySelectorAll('input,select,textarea').forEach(x=>x.disabled=true);if(!locked)overlay.querySelector('#record-form').onsubmit=async e=>{e.preventDefault();const msg=overlay.querySelector('#form-msg');msg.textContent='Saving…';const form=new FormData(e.currentTarget);const payload={};cfg.fields.forEach(([name,,type])=>{if(type==='checkbox')payload[name]=form.get(name)==='on';else{const raw=form.get(name);if(raw!==''&&raw!==null)payload[name]=type==='number'?Number(raw):raw;}});if(cfg.table==='investment_cases'&&payload.assumptions){try{payload.assumptions=JSON.parse(payload.assumptions);}catch{msg.textContent='Assumptions harus JSON valid.';return;}}try{if(!state.profile?.organization_id)throw new Error('Organization profile tidak tersedia.');if(!isEdit)payload.organization_id=state.profile.organization_id;const result=isEdit?await sb.from(cfg.table).update(payload).eq('id',row.id).select().single():await sb.from(cfg.table).insert(payload).select().single();if(result.error)throw result.error;overlay.remove();await renderPage(state.page);}catch(err){msg.textContent=err.message;}};}
async function removeRecord(cfg,id){if(!confirm(`Hapus ${cfg.singular} ini? Tindakan ini tidak dapat dibatalkan.`))return;try{const {error}=await sb.from(cfg.table).delete().eq('id',id);if(error)throw error;await renderPage(state.page);}catch(e){alert(`Gagal menghapus: ${e.message}`);}}
function exportCsv(cfg,rows){const lines=[cfg.labels.join(',')];rows.forEach(r=>lines.push(cfg.cols.map(c=>`"${String(r[c]??'').replace(/"/g,'""')}"`).join(',')));const blob=new Blob([lines.join('\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`adtrans-${cfg.table}-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href);}

async function route(){const hash=location.hash||'#home';if(hash==='#imcs'){if(!sb){login();return;}try{const {data:{session}}=await sb.auth.getSession();if(!session){login();return;}state.profile=await loadProfile();shell();}catch(e){login();setTimeout(()=>{const m=document.querySelector('#login-msg');if(m)m.textContent=e.message;},0);}return;}publicSite();}
if(sb)sb.auth.onAuthStateChange((event)=>{if(event==='SIGNED_OUT')route();});window.addEventListener('hashchange',route);route();
