import { createClient } from '@supabase/supabase-js';
import './style.css';
const url=import.meta.env.VITE_SUPABASE_URL, key=import.meta.env.VITE_SUPABASE_ANON_KEY;
const sb=url&&key?createClient(url,key):null;
const fmt=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n||0));
const app=document.querySelector('#app');
app.innerHTML=`<div class="shell"><aside><div class="brand"><span>AD</span><div><b>ADTRANS</b><small>REALINDO · IMCS</small></div></div><nav>${['Executive Cockpit','Land Bank','Property & Asset','Development','Investment','Finance','Contracts & Legal','Risk & Compliance','Governance','KPI & Alerts'].map((x,i)=>`<button class="nav ${i===0?'active':''}" data-page="${x}">${['⌂','▦','◈','◆','◇','Rp','§','!','✓','◉'][i]} ${x}</button>`).join('')}</nav><div class="sidefoot">CONTROL • GOVERN • GROW<br><span>v0.1 foundation</span></div></aside><main><header><div><div class="eyebrow">INTEGRATED MANAGEMENT CONTROL SYSTEM</div><h1 id="title">Executive Cockpit</h1></div><div class="status"><i></i> ${sb?'SUPABASE CONNECTED':'LOCAL / SUPABASE PENDING'}</div></header><section id="content"></section></main></div>`;
const content=document.querySelector('#content');
function dashboard(){content.innerHTML=`<div class="hero"><div><p class="eyebrow">ADTRANS REALINDO</p><h2>Control the portfolio.<br><em>Decide with evidence.</em></h2><p class="muted">Satu control plane untuk tanah, proyek properti, investasi, keuangan, risiko, kontrak dan tata kelola.</p></div><div class="signal"><span>CONTROL STATUS</span><strong>READY</strong><small>Data produksi hanya masuk melalui workflow tervalidasi.</small></div></div><div class="cards"><article><span>LAND BANK</span><b id="landArea">—</b><small>Total area terkontrol</small></article><article><span>PROJECT GDV</span><b id="gdv">—</b><small>Gross development value</small></article><article><span>COST CONTROL</span><b id="cost">—</b><small>Budget vs actual</small></article><article><span>OPEN RISKS</span><b id="risks">—</b><small>Material risk register</small></article></div><div class="grid"><div class="panel"><div class="panelhead"><h3>Management Control</h3><span>LIVE VIEW</span></div><div class="bars"><div><label>Portfolio readiness</label><div><i style="width:72%"></i></div><b>72%</b></div><div><label>Data governance</label><div><i style="width:94%"></i></div><b>94%</b></div><div><label>Migration readiness</label><div><i style="width:38%"></i></div><b>38%</b></div></div></div><div class="panel"><div class="panelhead"><h3>Control Principles</h3></div><ul class="principles"><li>Evidence before migration</li><li>RLS + role-based access</li><li>Approval & audit trail</li><li>No fabricated business data</li></ul></div></div>`; loadMetrics();}
async function loadMetrics(){if(!sb)return; try{const [{data:l},{data:p},{data:r}]=await Promise.all([sb.from('land_assets').select('area_m2'),sb.from('property_projects').select('gdv'),sb.from('project_risks').select('id').is('closed_at',null)]);document.querySelector('#landArea').textContent=(l||[]).reduce((a,x)=>a+Number(x.area_m2||0),0).toLocaleString('id-ID')+' m²';document.querySelector('#gdv').textContent=fmt((p||[]).reduce((a,x)=>a+Number(x.gdv||0),0));document.querySelector('#risks').textContent=(r||[]).length;}catch(e){console.warn(e)}}
function page(name){document.querySelector('#title').textContent=name;if(name==='Executive Cockpit')return dashboard();const map={"Land Bank":['LAND BANK','Register bidang tanah, legal documents, valuation, zoning, encumbrance dan development potential.'],"Property & Asset":['PROPERTY & ASSET','Portfolio properti dan lifecycle aset.'],"Development":['DEVELOPMENT CONTROL','Pipeline, planning, progress, budget, cost dan change control.'],"Investment":['INVESTMENT','Investment case, IRR, NPV, ROI dan approval.'],"Finance":['FINANCE CONTROL','Budget, transaction, cash position dan receivables.'],"Contracts & Legal":['CONTRACT & LEGAL','Kontrak, expiry monitoring dan legal document control.'],"Risk & Compliance":['RISK & COMPLIANCE','Risk register, exposure, mitigation dan compliance.'],"Governance":['GOVERNANCE','Approval matrix, segregation of duties dan audit trail.'],"KPI & Alerts":['KPI & MANAGEMENT ALERTS','KPI enterprise dan early-warning management alerts.']};let [h,d]=map[name]||['MODULE',''];content.innerHTML=`<div class="module"><div class="moduleicon">◆</div><p class="eyebrow">ADTRANS REALINDO IMCS</p><h2>${h}</h2><p class="muted">${d}</p><div class="notice"><strong>FOUNDATION MODE</strong><br>Module siap dihubungkan ke tabel Supabase dan workflow approval. Data legacy Akvisio belum dipromosikan ke production sampai mapping dan reconciliation disetujui.</div></div>`}
dashboard();document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');page(b.dataset.page)});
