import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://nfvkdqpxexfymzuwdorx.supabase.co';
const SUPABASE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.VITE_SUPABASE_ANON_KEY || 'sb_publishable_4BG89zR_2gWWWeLqqDzALw_Atx9jAJ6';
const sb = createClient(SUPABASE_URL, SUPABASE_KEY);
const esc = (v) => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));

const CSS = `
.md-page{display:grid;gap:16px}.md-toolbar{display:flex;justify-content:space-between;align-items:center;gap:12px;flex-wrap:wrap}.md-card{background:var(--surface,#fff);border:1px solid rgba(120,130,145,.18);border-radius:16px;padding:18px}.md-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.md-select{display:grid;gap:6px}.md-select label{font-size:12px;color:#697386;font-weight:700}.md-select select{width:100%;border:1px solid rgba(120,130,145,.25);border-radius:10px;background:var(--surface,#fff);padding:11px 12px;font:inherit}.md-list{display:grid;gap:7px;max-height:260px;overflow:auto}.md-row{display:flex;justify-content:space-between;gap:10px;padding:10px;border-radius:9px;background:rgba(120,130,145,.06)}.md-chip{font-size:11px;padding:3px 7px;border-radius:999px;background:rgba(120,130,145,.12)}.md-muted{color:#697386;font-size:13px}.md-empty{padding:22px;text-align:center;color:#697386;border:1px dashed rgba(120,130,145,.3);border-radius:12px}@media(max-width:900px){.md-grid{grid-template-columns:1fr 1fr}}@media(max-width:560px){.md-grid{grid-template-columns:1fr}}
`;
function style(){if(document.getElementById('master-data-css'))return;const s=document.createElement('style');s.id='master-data-css';s.textContent=CSS;document.head.appendChild(s)}
async function query(table,select='id,name,code',order='created_at'){const {data,error}=await sb.from(table).select(select).order(order,{ascending:false});if(error)throw error;return data||[]}
async function catalogs(){const {data,error}=await sb.from('master_data_catalogs').select('id,catalog_key,catalog_name').eq('active',true).order('catalog_name');if(error)throw error;return data||[]}
async function values(catalogId){const {data,error}=await sb.from('master_data_values').select('id,value_code,value_label,sort_order').eq('catalog_id',catalogId).eq('active',true).order('sort_order');if(error)throw error;return data||[]}
let data={projects:[],partners:[],inventory:[],warehouses:[],customers:[],employees:[],departments:[],accounts:[],catalogs:[],values:{}};

function selectHtml(id,label,items,placeholder='Pilih…',labelKey='name'){return `<div class="md-select"><label for="${id}">${esc(label)}</label><select id="${id}"><option value="">${esc(placeholder)}</option>${items.map(x=>`<option value="${esc(x.id||x.value_code)}">${esc(x[labelKey]||x.value_label||x.name||x.code)}</option>`).join('')}</select></div>`}
function render(){style();const host=document.querySelector('#content');if(!host)return;const projectTypes=data.values.PROJECT_TYPE||[];const inventoryCats=data.values.INVENTORY_CATEGORY||[];const uoms=data.values.UOM||[];host.innerHTML=`<div class="md-page"><div class="md-toolbar"><div><div class="eyebrow">MASTER DATA & QUICK SELECTOR</div><h2 style="margin:5px 0 0">Data & Dropdown</h2><div class="md-muted">Pusat pilihan data yang dipakai lintas Project, Procurement, Warehouse, Finance, HR dan Sales.</div></div></div><section class="md-card"><h3 style="margin-top:0">Quick selector</h3><div class="md-grid">${selectHtml('md-project','Jenis / Pilih Proyek',data.projects,'Pilih proyek…','name')}${selectHtml('md-project-type','Jenis Proyek',projectTypes,'Pilih jenis proyek…','value_label')}${selectHtml('md-partner','Supplier / Sub Contractor',data.partners,'Pilih mitra…','display_name')}${selectHtml('md-inventory','Inventori / Material',data.inventory,'Pilih inventori…','item_name')}${selectHtml('md-category','Kategori Inventori',inventoryCats,'Pilih kategori…','value_label')}${selectHtml('md-warehouse','Gudang',data.warehouses,'Pilih gudang…','warehouse_name')}${selectHtml('md-customer','Customer / Pembeli',data.customers,'Pilih customer…','full_name')}${selectHtml('md-employee','Karyawan',data.employees,'Pilih karyawan…','full_name')}${selectHtml('md-department','Department',data.departments,'Pilih department…','name')}${selectHtml('md-account','Akun Buku Besar',data.accounts,'Pilih akun…','account_name')}${selectHtml('md-uom','Satuan',uoms,'Pilih satuan…','value_label')}</div></section><section class="md-grid"><div class="md-card"><h3 style="margin-top:0">Supplier & Sub Contractor</h3><div class="md-list">${data.partners.length?data.partners.map(x=>`<div class="md-row"><span>${esc(x.display_name||x.legal_name)}<br><span class="md-muted">${esc(x.partner_code)}</span></span><span class="md-chip">${esc(x.partner_type)}</span></div>`).join(''):'<div class="md-empty">Belum ada data mitra.</div>'}</div></div><div class="md-card"><h3 style="margin-top:0">Inventory</h3><div class="md-list">${data.inventory.length?data.inventory.map(x=>`<div class="md-row"><span>${esc(x.item_name)}<br><span class="md-muted">${esc(x.item_code)} · ${esc(x.unit_of_measure)}</span></span><span class="md-chip">${esc(x.category)}</span></div>`).join(''):'<div class="md-empty">Belum ada item inventori.</div>'}</div></div><div class="md-card"><h3 style="margin-top:0">Customer</h3><div class="md-list">${data.customers.length?data.customers.map(x=>`<div class="md-row"><span>${esc(x.full_name)}<br><span class="md-muted">${esc(x.customer_code)}</span></span><span class="md-chip">${esc(x.status)}</span></div>`).join(''):'<div class="md-empty">Belum ada customer.</div>'}</div></div></section></div>`;}
async function load(){try{const [projects,partners,inventory,warehouses,customers,employees,departments,accounts,cats]=await Promise.all([query('property_projects','id,name,code','created_at'),query('business_partners','id,legal_name,display_name,partner_code,partner_type','created_at'),query('inventory_items','id,item_name,item_code,category,unit_of_measure','created_at'),query('warehouses','id,warehouse_name,warehouse_code','created_at'),query('customers','id,full_name,customer_code,status','created_at'),query('employees','id,full_name,employee_no','created_at'),query('departments','id,name,code','created_at'),query('chart_of_accounts','id,account_name,account_code,account_type','created_at'),catalogs()]);data={projects,partners,inventory,warehouses,customers,employees,departments,accounts,catalogs:cats,values:{}};await Promise.all(cats.map(async c=>{data.values[c.catalog_key]=await values(c.id)}));render()}catch(e){const c=document.querySelector('#content');if(c)c.innerHTML=`<div class="md-empty">Master data gagal dimuat: ${esc(e.message)}</div>`}}
function injectNav(){const nav=document.querySelector('aside nav');if(!nav||nav.querySelector('[data-master-data-nav]'))return;const b=document.createElement('button');b.className='nav';b.dataset.masterDataNav='1';b.innerHTML='<span>▾</span>Data & Dropdown';b.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');load()};nav.appendChild(b)}
const obs=new MutationObserver(injectNav);obs.observe(document.body,{childList:true,subtree:true});setInterval(injectNav,1500);injectNav();
