import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL=import.meta.env.VITE_SUPABASE_URL||'https://nfvkdqpxexfymzuwdorx.supabase.co';
const SUPABASE_KEY=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY||import.meta.env.VITE_SUPABASE_ANON_KEY||'sb_publishable_4BG89zR_2gWWWeLqqDzALw_Atx9jAJ6';
const sb=createClient(SUPABASE_URL,SUPABASE_KEY); let orgId=null,active='Contracts',search='';
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
const money=v=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(v||0));
const date=v=>v?new Intl.DateTimeFormat('id-ID',{dateStyle:'medium'}).format(new Date(v)):'—';
const tabs={Contracts:{table:'contracts',cols:['contract_no','title','contract_type','counterparty','start_date','end_date','value','status'],labels:['No','Title','Type','Counterparty','Start','End','Value','Status'],create:['contract_no','title','contract_type','counterparty','start_date','end_date','value']},Leases:{table:'lease_agreements',cols:['lease_no','tenant_name','property_id','start_date','end_date','base_rent','billing_frequency','status'],labels:['Lease','Tenant','Property','Start','End','Base Rent','Billing','Status'],create:['lease_no','tenant_name','start_date','end_date','base_rent','billing_frequency']},'Service Agreements':{table:'service_agreements',cols:['agreement_no','service_name','service_category','start_date','end_date','service_value','billing_frequency','status'],labels:['Agreement','Service','Category','Start','End','Value','Billing','Status'],create:['agreement_no','service_name','service_category','start_date','end_date','service_value','billing_frequency']},'Work Orders':{table:'work_orders',cols:['work_order_no','title','work_type','priority','status','scheduled_at','estimated_cost'],labels:['WO','Title','Type','Priority','Status','Scheduled','Estimate'],create:['work_order_no','title','work_type','priority','scheduled_at','estimated_cost']},'Payroll Link':{table:'enterprise_payroll_attendance_link',cols:['employee_no','full_name','period_start','period_end','gross_pay','net_pay','verified_events','exception_events','clock_in_events','clock_out_events'],labels:['Employee No','Employee','Start','End','Gross','Net','Verified','Exceptions','In','Out']}};
const labels={contract_no:'Contract No',title:'Title',contract_type:'Contract Type',counterparty:'Counterparty',start_date:'Start Date',end_date:'End Date',value:'Value',lease_no:'Lease No',tenant_name:'Tenant',base_rent:'Base Rent',billing_frequency:'Billing Frequency',agreement_no:'Agreement No',service_name:'Service Name',service_category:'Category',service_value:'Service Value',work_order_no:'WO No',work_type:'Work Type',priority:'Priority',scheduled_at:'Scheduled At',estimated_cost:'Estimated Cost'};
const styles=`.ops-view{display:grid;gap:16px}.ops-tabs{display:flex;flex-wrap:wrap;gap:8px}.ops-tabs button,.ops-action{border:1px solid #dfe3de;background:#fff;border-radius:10px;padding:9px 12px;cursor:pointer}.ops-tabs button.active,.ops-action.primary{background:#151b24;color:#fff}.ops-head{padding:20px;border:1px solid #e5e7eb;border-radius:16px;background:#fff}.ops-head h2{margin:5px 0}.ops-head p{color:#697386;max-width:850px}.ops-toolbar{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.ops-toolbar input{flex:1;min-width:220px;border:1px solid #dfe3de;border-radius:10px;padding:10px 12px}.ops-table{overflow:auto;border:1px solid #e5e7eb;border-radius:14px;background:#fff}.ops-table table{width:100%;border-collapse:collapse;min-width:900px}.ops-table th,.ops-table td{padding:11px 12px;border-bottom:1px solid #eef0ed;text-align:left;font-size:12px}.ops-table th{font-size:10px;letter-spacing:.06em;text-transform:uppercase;color:#697386}.ops-kpis{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px}.ops-kpi{padding:15px;border:1px solid #e5e7eb;border-radius:14px;background:#fff}.ops-kpi b{display:block;font-size:22px}.ops-kpi span{font-size:11px;color:#697386}.ops-note{padding:12px 14px;background:#fbfaf6;border-left:3px solid #b9852d;font-size:12px;color:#4c5562}.ops-form{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:10px;padding:14px;border:1px solid #e5e7eb;border-radius:14px;background:#fafbf9}.ops-form label{display:grid;gap:5px;font-size:11px;color:#697386}.ops-form input,.ops-form select{padding:9px;border:1px solid #dfe3de;border-radius:9px;background:#fff}.ops-msg{font-size:12px;color:#697386;grid-column:1/-1}`;
if(!document.querySelector('#operations-style')){const s=document.createElement('style');s.id='operations-style';s.textContent=styles;document.head.appendChild(s);}
async function context(){if(orgId)return orgId;const {data:{user},error:e}=await sb.auth.getUser();if(e||!user)return null;const {data,error}=await sb.from('profiles').select('organization_id,active').eq('id',user.id).maybeSingle();if(error)throw error;if(!data?.active)throw new Error('Profile tidak aktif.');orgId=data.organization_id;return orgId;}
async function load(tab){const org=await context();if(!org)return[];const c=tabs[tab];let q=sb.from(c.table).select(c.cols.join(','));q=q.eq('organization_id',org).limit(100);if(c.table==='contracts')q=q.order('start_date',{ascending:false});else if(c.table==='lease_agreements'||c.table==='service_agreements')q=q.order('end_date');else if(c.table==='work_orders')q=q.order('scheduled_at',{ascending:false});else q=q.order('period_start',{ascending:false});const {data,error}=await q;if(error)throw error;return data||[];}
function fmt(c,v){if(v==null||v==='')return'—';if(['value','base_rent','service_value','estimated_cost','gross_pay','net_pay'].includes(c))return esc(money(v));if(c.includes('date')||c.endsWith('_at'))return esc(date(v));return esc(v);}
function form(tab){const c=tabs[tab];if(!c.create)return'';return`<form id="ops-create" class="ops-form">${c.create.map(k=>`<label>${esc(labels[k]||k)}<input name="${k}" type="${k.includes('date')?'date':k.includes('cost')||['value','base_rent','service_value'].includes(k)?'number':k==='scheduled_at'?'datetime-local':'text'}" ${['contract_no','title','lease_no','tenant_name','agreement_no','service_name','work_order_no'].includes(k)?'required':''}></label>`).join('')}<span class="ops-msg" id="ops-msg"></span><button class="ops-action primary" type="submit">Save record</button></form>`;}
async function createRecord(tab,f){const org=await context();if(!org)throw new Error('Session tidak valid.');const c=tabs[tab],raw=Object.fromEntries(new FormData(f).entries()),p={organization_id:org,...raw};if(['contracts','lease_agreements','service_agreements','work_orders'].includes(c.table))p.status='DRAFT';if(c.table==='work_orders')p.priority=p.priority||'NORMAL';for(const k of Object.keys(p)){if(p[k]==='')delete p[k];if(['value','base_rent','service_value','estimated_cost'].includes(k)&&p[k]!=null)p[k]=Number(p[k]);}const {error}=await sb.from(c.table).insert(p);if(error)throw error;}
async function render(){const root=document.querySelector('#content');if(!root)return;root.innerHTML=`<div class="ops-view"><div class="ops-head"><h2>Enterprise Operations</h2><p>Contract, lease, service delivery, work order dan payroll-attendance control. Organization scope selalu diambil dari profile authenticated user, bukan hard-coded.</p></div><div class="ops-tabs">${Object.keys(tabs).map(t=>`<button class="${t===active?'active':''}" data-ops-tab="${esc(t)}">${esc(t)}</button>`).join('')}</div>${form(active)}<div class="ops-toolbar"><input id="ops-search" placeholder="Search visible records…" value="${esc(search)}"><button class="ops-action" id="ops-refresh">↻ Refresh</button></div><div id="ops-body">Loading…</div></div>`;document.querySelectorAll('[data-ops-tab]').forEach(b=>b.onclick=()=>{active=b.dataset.opsTab;search='';render();});document.querySelector('#ops-search').oninput=e=>{search=e.target.value.toLowerCase();filterRows();};document.querySelector('#ops-refresh').onclick=render;const f=document.querySelector('#ops-create');if(f)f.onsubmit=async e=>{e.preventDefault();const m=document.querySelector('#ops-msg');m.textContent='Saving…';try{await createRecord(active,f);m.textContent='Saved.';f.reset();await render();}catch(err){m.textContent=`Save gagal: ${err.message}`;}};try{window.__opsRows=await load(active);filterRows();}catch(e){document.querySelector('#ops-body').innerHTML=`<div class="ops-note">Operations gagal dimuat: ${esc(e.message)}</div>`;}}
function filterRows(){const body=document.querySelector('#ops-body');if(!body)return;const rows=(window.__opsRows||[]).filter(r=>!search||Object.values(r).some(v=>String(v??'').toLowerCase().includes(search)));const c=tabs[active];body.innerHTML=`<div class="ops-kpis"><div class="ops-kpi"><b>${rows.length}</b><span>Visible records</span></div><div class="ops-kpi"><b>${rows.filter(r=>['ACTIVE','OPEN','DRAFT'].includes(r.status)).length}</b><span>Active / open</span></div><div class="ops-kpi"><b>${rows.filter(r=>['OVERDUE','EXCEPTION'].includes(r.status)).length}</b><span>Attention</span></div></div><div class="ops-table"><table><thead><tr>${c.labels.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${c.cols.map(k=>`<td>${fmt(k,r[k])}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${c.cols.length}">No authorized records.</td></tr>`}</tbody></table></div><div class="ops-note">All reads/writes are constrained by the authenticated organization and Supabase RLS.</div>`;}
function injectNav(){const nav=document.querySelector('aside nav');if(!nav||nav.querySelector('[data-page="Enterprise Operations"]'))return;const b=document.createElement('button');b.className='nav';b.dataset.page='Enterprise Operations';b.innerHTML='<span>▤</span>Enterprise Operations';b.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');const t=document.querySelector('#page-title');if(t)t.textContent='Enterprise Operations';render();};nav.insertBefore(b,nav.children[1]||null);}
new MutationObserver(injectNav).observe(document.body,{childList:true,subtree:true});injectNav();