import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://nfvkdqpxexfymzuwdorx.supabase.co';
const SUPABASE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.VITE_SUPABASE_ANON_KEY || 'sb_publishable_4BG89zR_2gWWWeLqqDzALw_Atx9jAJ6';
const sb = createClient(SUPABASE_URL, SUPABASE_KEY);
const esc = v => String(v ?? '').replace(/[&<>\"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
const money = v => new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(v||0));
const date = v => v ? new Intl.DateTimeFormat('id-ID',{dateStyle:'medium'}).format(new Date(v)) : '—';
const ORG = 'b68a13a7-15b2-47b1-9ce2-024da729e6a4';
const tabs = {
  Contracts:{table:'contracts',title:'CONTRACT REGISTER',cols:['contract_no','title','contract_type','counterparty','start_date','end_date','value','status'],labels:['No','Title','Type','Counterparty','Start','End','Value','Status']},
  Leases:{table:'lease_agreements',title:'LEASE MANAGEMENT',cols:['lease_no','tenant_name','property_id','start_date','end_date','base_rent','billing_frequency','status'],labels:['Lease','Tenant','Property','Start','End','Base Rent','Billing','Status']},
  'Service Agreements':{table:'service_agreements',title:'SERVICE AGREEMENTS',cols:['agreement_no','service_name','service_category','start_date','end_date','service_value','billing_frequency','status'],labels:['Agreement','Service','Category','Start','End','Value','Billing','Status']},
  'Work Orders':{table:'work_orders',title:'WORK ORDERS',cols:['work_order_no','title','work_type','priority','status','scheduled_at','estimated_cost'],labels:['WO','Title','Type','Priority','Status','Scheduled','Estimate']},
  'Payroll Link':{table:'payroll_attendance_summaries',title:'PAYROLL / ATTENDANCE LINK',cols:['employee_id','period_start','period_end','attendance_days','verified_events','exception_events','overtime_hours'],labels:['Employee','Start','End','Days','Verified','Exceptions','OT Hours']}
};
const styles=`.ops-view{display:grid;gap:16px}.ops-tabs{display:flex;flex-wrap:wrap;gap:8px}.ops-tabs button{border:1px solid #dfe3de;background:#fff;border-radius:10px;padding:9px 12px;cursor:pointer}.ops-tabs button.active{background:#151b24;color:#fff}.ops-head{padding:20px;border:1px solid #e5e7eb;border-radius:16px;background:#fff}.ops-head h2{margin:5px 0}.ops-head p{color:#697386;max-width:850px}.ops-table{overflow:auto;border:1px solid #e5e7eb;border-radius:14px;background:#fff}.ops-table table{width:100%;border-collapse:collapse;min-width:850px}.ops-table th,.ops-table td{padding:11px 12px;border-bottom:1px solid #eef0ed;text-align:left;font-size:12px}.ops-table th{font-size:10px;letter-spacing:.06em;text-transform:uppercase;color:#697386}.ops-kpis{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px}.ops-kpi{padding:15px;border:1px solid #e5e7eb;border-radius:14px;background:#fff}.ops-kpi b{display:block;font-size:22px}.ops-kpi span{font-size:11px;color:#697386}.ops-note{padding:12px 14px;background:#fbfaf6;border-left:3px solid #b9852d;font-size:12px;color:#4c5562}`;
if(!document.querySelector('#operations-style')){const s=document.createElement('style');s.id='operations-style';s.textContent=styles;document.head.appendChild(s);}
let active='Contracts';
async function load(tab){const cfg=tabs[tab];let q=sb.from(cfg.table).select(cfg.cols.join(','));if(cfg.table==='contracts')q=q.eq('organization_id',ORG).order('start_date',{ascending:false}).limit(100);else if(cfg.table==='lease_agreements')q=q.eq('organization_id',ORG).order('end_date').limit(100);else if(cfg.table==='service_agreements')q=q.eq('organization_id',ORG).order('end_date').limit(100);else if(cfg.table==='work_orders')q=q.eq('organization_id',ORG).order('scheduled_at',{ascending:false}).limit(100);else q=q.eq('organization_id',ORG).order('period_start',{ascending:false}).limit(100);const {data,error}=await q;if(error)throw error;return data||[];}
function fmt(col,v){if(v==null||v==='')return '—';if(['value','base_rent','service_value','estimated_cost'].includes(col))return esc(money(v));if(col.includes('date')||col.endsWith('_at'))return esc(date(v));return esc(v);}
async function render(){const root=document.querySelector('#content');if(!root)return;root.innerHTML=`<div class="ops-view"><div class="ops-head"><div class="eyebrow">ENTERPRISE OPERATIONS</div><h2>Contracts, Leasing & Service Delivery</h2><p>Operational control untuk kontrak, lease, service agreement, work order dan hubungan attendance-to-payroll. Semua data organization-scoped dan tetap tunduk pada RLS.</p></div><div class="ops-tabs">${Object.keys(tabs).map(t=>`<button class="${t===active?'active':''}" data-ops-tab="${esc(t)}">${esc(t)}</button>`).join('')}</div><div id="ops-body"><div class="muted">Loading…</div></div></div>`;document.querySelectorAll('[data-ops-tab]').forEach(b=>b.onclick=()=>{active=b.dataset.opsTab;render();});try{const rows=await load(active);const cfg=tabs[active];const counts=rows.length;const body=document.querySelector('#ops-body');body.innerHTML=`<div class="ops-kpis"><div class="ops-kpi"><b>${counts}</b><span>Visible records</span></div><div class="ops-kpi"><b>${rows.filter(r=>['ACTIVE','OPEN','DUE'].includes(r.status)).length}</b><span>Active / open</span></div><div class="ops-kpi"><b>${rows.filter(r=>['OVERDUE','EXCEPTION'].includes(r.status)).length}</b><span>Attention</span></div></div><div class="ops-table"><table><thead><tr>${cfg.labels.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${cfg.cols.map(c=>`<td>${fmt(c,r[c])}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${cfg.cols.length}">No authorized records.</td></tr>`}</tbody></table></div><div class="ops-note">Write operations remain governed by the existing role/RLS policies. Posted financial transactions are not destructively deleted; lifecycle changes must use controlled transition/reversal workflows.</div>`;}catch(e){document.querySelector('#ops-body').innerHTML=`<div class="form-msg">Operations gagal dimuat: ${esc(e.message)}</div>`;console.error('[Operations]',e);}}
function injectNav(){const nav=document.querySelector('aside nav');if(!nav||nav.querySelector('[data-page="Enterprise Operations"]'))return;const b=document.createElement('button');b.className='nav';b.dataset.page='Enterprise Operations';b.innerHTML='<span>▤</span>Enterprise Operations';b.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');const t=document.querySelector('#page-title');if(t)t.textContent='Enterprise Operations';render();};nav.insertBefore(b,nav.children[1]||null);}
const observer=new MutationObserver(injectNav);observer.observe(document.body,{childList:true,subtree:true});injectNav();