import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://nfvkdqpxexfymzuwdorx.supabase.co';
const SUPABASE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.VITE_SUPABASE_ANON_KEY || 'sb_publishable_4BG89zR_2gWWWeLqqDzALw_Atx9jAJ6';
const sb = createClient(SUPABASE_URL, SUPABASE_KEY);
const ORG = 'b68a13a7-15b2-47b1-9ce2-024da729e6a4';
const esc = v => String(v ?? '').replace(/[&<>\"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
const money = v => new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(v||0));
const date = v => v ? new Intl.DateTimeFormat('id-ID',{dateStyle:'medium'}).format(new Date(v)) : '—';
const tabs = {
  Contracts:{table:'contracts',title:'CONTRACT REGISTER',cols:['contract_no','title','contract_type','counterparty','start_date','end_date','value','status'],labels:['No','Title','Type','Counterparty','Start','End','Value','Status'],create:['contract_no','title','contract_type','counterparty','start_date','end_date','value']},
  Leases:{table:'lease_agreements',title:'LEASE MANAGEMENT',cols:['lease_no','tenant_name','property_id','start_date','end_date','base_rent','billing_frequency','status'],labels:['Lease','Tenant','Property','Start','End','Base Rent','Billing','Status'],create:['lease_no','tenant_name','start_date','end_date','base_rent','billing_frequency']},
  'Service Agreements':{table:'service_agreements',title:'SERVICE AGREEMENTS',cols:['agreement_no','service_name','service_category','start_date','end_date','service_value','billing_frequency','status'],labels:['Agreement','Service','Category','Start','End','Value','Billing','Status'],create:['agreement_no','service_name','service_category','start_date','end_date','service_value','billing_frequency']},
  'Work Orders':{table:'work_orders',title:'WORK ORDERS',cols:['work_order_no','title','work_type','priority','status','scheduled_at','estimated_cost'],labels:['WO','Title','Type','Priority','Status','Scheduled','Estimate'],create:['work_order_no','title','work_type','priority','scheduled_at','estimated_cost']},
  'Payroll Link':{table:'enterprise_payroll_attendance_link',title:'PAYROLL / ATTENDANCE LINK',cols:['employee_no','full_name','period_start','period_end','gross_pay','net_pay','verified_events','exception_events','clock_in_events','clock_out_events'],labels:['Employee No','Employee','Start','End','Gross','Net','Verified','Exceptions','In','Out']}
};
const fieldLabels={contract_no:'Contract No',title:'Title',contract_type:'Contract Type',counterparty:'Counterparty',start_date:'Start Date',end_date:'End Date',value:'Value',lease_no:'Lease No',tenant_name:'Tenant',base_rent:'Base Rent',billing_frequency:'Billing Frequency',agreement_no:'Agreement No',service_name:'Service Name',service_category:'Category',service_value:'Service Value',work_order_no:'WO No',work_type:'Work Type',priority:'Priority',scheduled_at:'Scheduled At',estimated_cost:'Estimated Cost'};
const styles=`.ops-view{display:grid;gap:16px}.ops-tabs{display:flex;flex-wrap:wrap;gap:8px}.ops-tabs button,.ops-action{border:1px solid #dfe3de;background:#fff;border-radius:10px;padding:9px 12px;cursor:pointer}.ops-tabs button.active,.ops-action.primary{background:#151b24;color:#fff}.ops-head{padding:20px;border:1px solid #e5e7eb;border-radius:16px;background:#fff}.ops-head h2{margin:5px 0}.ops-head p{color:#697386;max-width:850px}.ops-toolbar{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.ops-toolbar input{flex:1;min-width:220px;border:1px solid #dfe3de;border-radius:10px;padding:10px 12px}.ops-table{overflow:auto;border:1px solid #e5e7eb;border-radius:14px;background:#fff}.ops-table table{width:100%;border-collapse:collapse;min-width:900px}.ops-table th,.ops-table td{padding:11px 12px;border-bottom:1px solid #eef0ed;text-align:left;font-size:12px}.ops-table th{font-size:10px;letter-spacing:.06em;text-transform:uppercase;color:#697386}.ops-kpis{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px}.ops-kpi{padding:15px;border:1px solid #e5e7eb;border-radius:14px;background:#fff}.ops-kpi b{display:block;font-size:22px}.ops-kpi span{font-size:11px;color:#697386}.ops-note{padding:12px 14px;background:#fbfaf6;border-left:3px solid #b9852d;font-size:12px;color:#4c5562}.ops-form{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:10px;padding:14px;border:1px solid #e5e7eb;border-radius:14px;background:#fafbf9}.ops-form label{display:grid;gap:5px;font-size:11px;color:#697386}.ops-form input,.ops-form select{padding:9px;border:1px solid #dfe3de;border-radius:9px;background:#fff}.ops-form .wide{grid-column:1/-1}.ops-msg{font-size:12px;color:#697386;grid-column:1/-1}`;
if(!document.querySelector('#operations-style')){const s=document.createElement('style');s.id='operations-style';s.textContent=styles;document.head.appendChild(s);}
let active='Contracts', search='', busy=false;
async function load(tab){const cfg=tabs[tab];let q=sb.from(cfg.table).select(cfg.cols.join(','));if(cfg.table==='contracts')q=q.eq('organization_id',ORG).order('start_date',{ascending:false}).limit(100);else if(cfg.table==='lease_agreements')q=q.eq('organization_id',ORG).order('end_date').limit(100);else if(cfg.table==='service_agreements')q=q.eq('organization_id',ORG).order('end_date').limit(100);else if(cfg.table==='work_orders')q=q.eq('organization_id',ORG).order('scheduled_at',{ascending:false}).limit(100);else q=q.eq('organization_id',ORG).order('period_start',{ascending:false}).limit(100);const {data,error}=await q;if(error)throw error;return data||[];}
function fmt(col,v){if(v==null||v==='')return '—';if(['value','base_rent','service_value','estimated_cost','gross_pay','net_pay'].includes(col))return esc(money(v));if(col.includes('date')||col.endsWith('_at'))return esc(date(v));return esc(v);}
function form(tab){const cfg=tabs[tab];if(!cfg.create)return '';return `<form id="ops-create" class="ops-form">${cfg.create.map(c=>`<label>${esc(fieldLabels[c]||c)}<input name="${esc(c)}" type="${c.includes('date')?'date':c.includes('cost')||['value','base_rent','service_value'].includes(c)?'number':c==='scheduled_at'?'datetime-local':'text'}" ${['contract_no','title','lease_no','tenant_name','agreement_no','service_name','work_order_no'].includes(c)?'required':''}></label>`).join('')}<div class="ops-msg" id="ops-msg"></div><button class="ops-action primary" type="submit" ${busy?'disabled':''}>Save record</button></form>`;}
async function createRecord(tab,formEl){const cfg=tabs[tab];const raw=Object.fromEntries(new FormData(formEl).entries());const payload={organization_id:ORG,...raw};if(cfg.table==='contracts')payload.status='DRAFT';if(cfg.table==='lease_agreements')payload.status='DRAFT';if(cfg.table==='service_agreements')payload.status='DRAFT';if(cfg.table==='work_orders'){payload.status='DRAFT';payload.priority=payload.priority||'NORMAL';}for(const k of Object.keys(payload)){if(payload[k]==='')delete payload[k];if(['value','base_rent','service_value','estimated_cost'].includes(k)&&payload[k]!=null)payload[k]=Number(payload[k]);}const {error}=await sb.from(cfg.table).insert(payload);if(error)throw error;}
async function render(){const root=document.querySelector('#content');if(!root)return;root.innerHTML=`<div class="ops-view"><div class="ops-head"><div class="eyebrow">ENTERPRISE OPERATIONS</div><h2>Contracts, Leasing & Service Delivery</h2><p>Operational control untuk contract, lease, service agreement, work order dan rekonsiliasi attendance-to-payroll. Semua write tunduk pada Auth/RLS.</p></div><div class="ops-tabs">${Object.keys(tabs).map(t=>`<button class="${t===active?'active':''}" data-ops-tab="${esc(t)}">${esc(t)}</button>`).join('')}</div>${form(active)}<div class="ops-toolbar"><input id="ops-search" placeholder="Search visible records…" value="${esc(search)}"><button class="ops-action" id="ops-refresh">↻ Refresh</button></div><div id="ops-body"><div class="muted">Loading…</div></div></div>`;document.querySelectorAll('[data-ops-tab]').forEach(b=>b.onclick=()=>{active=b.dataset.opsTab;search='';render();});document.querySelector('#ops-search').oninput=e=>{search=e.target.value.toLowerCase();filterRows();};document.querySelector('#ops-refresh').onclick=render;const f=document.querySelector('#ops-create');if(f)f.onsubmit=async e=>{e.preventDefault();const msg=document.querySelector('#ops-msg');msg.textContent='Saving…';try{await createRecord(active,f);msg.textContent='Saved. Reloading…';f.reset();await render();}catch(err){msg.textContent=`Save gagal: ${err.message}`;}};try{window.__opsRows=await load(active);filterRows();}catch(e){document.querySelector('#ops-body').innerHTML=`<div class="form-msg">Operations gagal dimuat: ${esc(e.message)}</div>`;console.error('[Operations]',e);}}
function filterRows(){const body=document.querySelector('#ops-body');if(!body)return;const rows=(window.__opsRows||[]).filter(r=>!search||Object.values(r).some(v=>String(v??'').toLowerCase().includes(search)));const cfg=tabs[active];body.innerHTML=`<div class="ops-kpis"><div class="ops-kpi"><b>${rows.length}</b><span>Visible records</span></div><div class="ops-kpi"><b>${rows.filter(r=>['ACTIVE','OPEN','DRAFT'].includes(r.status)).length}</b><span>Active / open</span></div><div class="ops-kpi"><b>${rows.filter(r=>['OVERDUE','EXCEPTION'].includes(r.status)).length}</b><span>Attention</span></div></div><div class="ops-table"><table><thead><tr>${cfg.labels.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${cfg.cols.map(c=>`<td>${fmt(c,r[c])}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${cfg.cols.length}">No authorized records.</td></tr>`}</tbody></table></div><div class="ops-note">Lifecycle control: Draft → Submit → Approve → Post. Posted finance records must use reversal, not destructive deletion.</div>`;}
function injectNav(){const nav=document.querySelector('aside nav');if(!nav||nav.querySelector('[data-page="Enterprise Operations"]'))return;const b=document.createElement('button');b.className='nav';b.dataset.page='Enterprise Operations';b.innerHTML='<span>▤</span>Enterprise Operations';b.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');const t=document.querySelector('#page-title');if(t)t.textContent='Enterprise Operations';render();};nav.insertBefore(b,nav.children[1]||null);}
const observer=new MutationObserver(injectNav);observer.observe(document.body,{childList:true,subtree:true});injectNav();