const app = document.querySelector('#app');

const portfolioCSS = `
:root{--gold:#c8a86b;--ink:#0b0d0f;--paper:#f4f1ea;--muted:#7b7f82;--line:#d8d4cc;--navy:#111820}
.public-corporate{font-family:Inter,Manrope,Arial,sans-serif;background:var(--paper);color:var(--ink);min-height:100vh}
.public-corporate *{box-sizing:border-box}.public-corporate a{text-decoration:none;color:inherit}
.pc-nav{position:sticky;top:0;z-index:50;background:rgba(244,241,234,.94);backdrop-filter:blur(18px);border-bottom:1px solid rgba(0,0,0,.08);display:flex;align-items:center;justify-content:space-between;padding:20px clamp(22px,5vw,80px)}
.pc-brand{display:flex;align-items:center;gap:12px;font-weight:900;letter-spacing:.08em}.pc-mark{width:42px;height:42px;border:1px solid var(--gold);display:grid;place-items:center;font-size:14px}.pc-brand small{display:block;font-size:9px;letter-spacing:.25em;color:#777;margin-top:3px}.pc-navlinks{display:flex;gap:28px;font-size:13px;font-weight:700}.pc-navlinks a:hover{color:#9b793b}.pc-login{border:1px solid #1a1d20;padding:11px 17px;font-size:12px;font-weight:800}
.pc-hero{min-height:760px;padding:90px clamp(22px,7vw,110px);display:grid;grid-template-columns:1.1fr .9fr;align-items:center;background:linear-gradient(120deg,#f7f4ed 0%,#ebe5d8 100%);position:relative;overflow:hidden}.pc-hero:after{content:'';position:absolute;width:620px;height:620px;border:1px solid rgba(155,121,59,.22);border-radius:50%;right:-180px;top:-140px;box-shadow:0 0 0 70px rgba(155,121,59,.04),0 0 0 140px rgba(155,121,59,.025)}
.pc-kicker{font-size:11px;letter-spacing:.3em;font-weight:900;color:#94743c}.pc-hero h1{font-size:clamp(52px,7vw,105px);line-height:.92;letter-spacing:-.055em;margin:22px 0;max-width:900px}.pc-hero h1 em{font-style:normal;color:#9a773b}.pc-hero p{max-width:650px;color:#555a5e;font-size:18px;line-height:1.8}.pc-actions{display:flex;gap:12px;margin-top:35px;flex-wrap:wrap}.pc-btn{padding:15px 22px;font-size:12px;font-weight:900;letter-spacing:.08em}.pc-btn.primary{background:#171b1e;color:#fff}.pc-btn.outline{border:1px solid #a6a29b}.pc-hero-card{position:relative;z-index:2;margin-left:auto;width:min(430px,100%);background:#12171b;color:#fff;padding:38px;box-shadow:30px 30px 0 rgba(155,121,59,.18)}.pc-hero-card .big{font-size:72px;font-weight:900;color:var(--gold);line-height:1}.pc-hero-card h3{font-size:24px;margin:18px 0 10px}.pc-hero-card p{font-size:14px;color:#aeb4b7;line-height:1.7}
.pc-strip{background:#171b1e;color:#fff;padding:24px clamp(22px,7vw,110px);display:grid;grid-template-columns:repeat(4,1fr);gap:20px}.pc-strip b{display:block;color:var(--gold);font-size:11px;letter-spacing:.16em;margin-bottom:7px}.pc-strip span{font-size:13px;color:#c4c8ca}
.pc-section{padding:110px clamp(22px,7vw,110px)}.pc-section.dark{background:#111820;color:#fff}.pc-section-head{display:grid;grid-template-columns:.8fr 1.2fr;gap:50px;margin-bottom:55px}.pc-label{font-size:10px;letter-spacing:.28em;color:#9b793b;font-weight:900}.pc-section h2{font-size:clamp(38px,5vw,70px);line-height:1;letter-spacing:-.04em;margin:0}.pc-section h2 em{font-style:normal;color:#a37e3f}.pc-copy{color:#697075;line-height:1.8;font-size:16px;max-width:680px}.dark .pc-copy{color:#aab0b4}
.pc-cards{display:grid;grid-template-columns:repeat(3,1fr);gap:1px;background:#cfc9bd}.pc-card{background:var(--paper);padding:38px;min-height:260px}.dark .pc-card{background:#182028;color:#fff}.pc-card .num{font-size:12px;color:#a07d42;font-weight:900}.pc-card h3{font-size:25px;margin:55px 0 12px}.pc-card p{color:#6d7275;line-height:1.7;font-size:14px}.dark .pc-card p{color:#aeb5b9}
.pc-projects{display:grid;grid-template-columns:1.25fr .75fr;gap:22px}.pc-project{min-height:330px;padding:35px;display:flex;flex-direction:column;justify-content:flex-end;background:linear-gradient(145deg,#283139,#111820);color:#fff;position:relative;overflow:hidden}.pc-project:before{content:'';position:absolute;inset:0;background:linear-gradient(135deg,transparent 45%,rgba(200,168,107,.22));}.pc-project>*{position:relative}.pc-project.small{min-height:154px}.pc-project h3{font-size:32px;margin:8px 0}.pc-project p{color:#c1c6c9;max-width:580px;line-height:1.6}.pc-projects-side{display:grid;gap:22px}
.pc-govern{display:grid;grid-template-columns:1fr 1fr;gap:70px;align-items:center}.pc-list{border-top:1px solid #353d44}.pc-list div{display:flex;gap:20px;padding:22px 0;border-bottom:1px solid #353d44}.pc-list b{color:var(--gold);min-width:32px}.pc-list span{color:#d5d9db}
.pc-contact{background:#c8a86b;padding:80px clamp(22px,7vw,110px);display:flex;align-items:center;justify-content:space-between;gap:30px}.pc-contact h2{font-size:clamp(42px,6vw,78px);line-height:.95;margin:12px 0}.pc-contact p{max-width:620px;color:#403822;line-height:1.7}.pc-contact .pc-btn{background:#111820;color:#fff}
.pc-footer{background:#0b0d0f;color:#92999e;padding:35px clamp(22px,7vw,110px);display:flex;justify-content:space-between;font-size:11px;letter-spacing:.12em}.pc-mobile{display:none}
@media(max-width:850px){.pc-navlinks{display:none}.pc-mobile{display:block}.pc-hero{grid-template-columns:1fr;padding-top:70px}.pc-hero-card{margin:55px 0 0}.pc-strip{grid-template-columns:1fr 1fr}.pc-section-head,.pc-govern,.pc-projects{grid-template-columns:1fr}.pc-cards{grid-template-columns:1fr}.pc-contact,.pc-footer{display:block}.pc-footer span{display:block;margin:8px 0}}
`;

function inject(){
  if(document.getElementById('pc-style')) return;
  const style=document.createElement('style');style.id='pc-style';style.textContent=portfolioCSS;document.head.appendChild(style);
}

function renderPortfolio(){
  if((location.hash||'').toLowerCase()==='#imcs') return;
  inject();document.title='ADTrans RealIndo | Corporate Portfolio';
  app.innerHTML=`<div class="public-corporate">
  <header class="pc-nav"><a href="#home" class="pc-brand"><span class="pc-mark">AD</span><span>ADTRANS<small>REALINDO</small></span></a><nav class="pc-navlinks"><a href="#about">ABOUT</a><a href="#business">BUSINESS</a><a href="#projects">PORTFOLIO</a><a href="#governance">GOVERNANCE</a><a href="#contact">CONTACT</a></nav><a class="pc-login" href="#imcs">IMCS LOGIN →</a><span class="pc-mobile">☰</span></header>
  <main>
   <section id="home" class="pc-hero"><div><div class="pc-kicker">PT ADTRANS REALINDO · CORPORATE PORTFOLIO</div><h1>We create <em>real value</em> from strategic assets.</h1><p>ADTrans RealIndo adalah platform pengembangan properti dan investasi yang mengintegrasikan strategic land, development, capital partnership dan governance untuk membangun aset yang bernilai dan berkelanjutan.</p><div class="pc-actions"><a class="pc-btn primary" href="#projects">VIEW PORTFOLIO →</a><a class="pc-btn outline" href="#contact">PARTNER WITH US</a></div></div><div class="pc-hero-card"><div class="big">01</div><h3>Property. Capital. Governance.</h3><p>Our operating philosophy connects opportunity with disciplined execution, transparent decisions and measurable outcomes.</p></div></section>
   <section class="pc-strip"><div><b>01 · ASSETS</b><span>Strategic Land Intelligence</span></div><div><b>02 · DEVELOPMENT</b><span>Project & Delivery Control</span></div><div><b>03 · CAPITAL</b><span>Investment Partnerships</span></div><div><b>04 · GOVERNANCE</b><span>Evidence-based Management</span></div></section>
   <section id="about" class="pc-section"><div class="pc-section-head"><div class="pc-label">01 · ABOUT ADTRANS REALINDO</div><div><h2>Built to turn <em>opportunity</em> into enduring value.</h2><p class="pc-copy">Kami membangun ekosistem bisnis properti yang menghubungkan aset, modal, pengembangan dan pengendalian dalam satu kerangka kerja. Fokus kami adalah kualitas keputusan sebelum kualitas eksekusi.</p></div></div><div class="pc-cards"><article class="pc-card"><div class="num">01</div><h3>Strategic Assets</h3><p>Identifikasi, legal validation, valuation, zoning dan development potential sebagai fondasi keputusan.</p></article><article class="pc-card"><div class="num">02</div><h3>Development</h3><p>Feasibility, design, cost, schedule, procurement, construction dan delivery dalam satu control model.</p></article><article class="pc-card"><div class="num">03</div><h3>Capital</h3><p>Investment case yang transparan, risk-adjusted return dan partnership governance yang dapat dipertanggungjawabkan.</p></article></div></section>
   <section id="business" class="pc-section dark"><div class="pc-section-head"><div class="pc-label">02 · BUSINESS PLATFORM</div><div><h2>Four disciplines.<br><em>One operating model.</em></h2><p class="pc-copy">Setiap opportunity bergerak melalui tahapan validasi dan governance sebelum menjadi commitment.</p></div></div><div class="pc-list"><div><b>LAND</b><span>Land bank, legal due diligence, valuation, zoning & highest-best-use.</span></div><div><b>BUILD</b><span>Development feasibility, project controls, procurement & delivery.</span></div><div><b>CAPITAL</b><span>Investment structuring, financial modelling, partnership & funding.</span></div><div><b>CONTROL</b><span>Risk, contracts, approvals, KPI, audit trail & management alerts.</span></div></div></section>
   <section id="projects" class="pc-section"><div class="pc-section-head"><div class="pc-label">03 · PORTFOLIO</div><div><h2>Selected <em>opportunity</em> platforms.</h2><p class="pc-copy">Public portfolio menampilkan kategori dan kapabilitas. Detail project, financial data dan sensitive information tetap berada di dalam IMCS.</p></div></div><div class="pc-projects"><article class="pc-project"><div class="pc-label">STRATEGIC LAND</div><h3>Land & Asset Platform</h3><p>Strategic land opportunities with legal, market and development intelligence.</p></article><div class="pc-projects-side"><article class="pc-project small"><div class="pc-label">PROPERTY DEVELOPMENT</div><h3>Residential & Mixed Use</h3></article><article class="pc-project small"><div class="pc-label">INVESTMENT</div><h3>Capital Partnerships</h3></article></div></div></section>
   <section id="governance" class="pc-section dark"><div class="pc-govern"><div><div class="pc-label">04 · GOVERNANCE</div><h2>Trust is built on <em>evidence.</em></h2><p class="pc-copy">ADTrans RealIndo menempatkan governance sebagai bagian dari operating system: data, approval, risk, contract dan accountability berjalan bersama.</p></div><div class="pc-list"><div><b>01</b><span>Validated data</span></div><div><b>02</b><span>Segregation of duties</span></div><div><b>03</b><span>Documented approvals</span></div><div><b>04</b><span>Continuous management control</span></div></div></div></section>
   <section id="contact" class="pc-contact"><div><div class="pc-label">05 · CONTACT</div><h2>Let's build<br>the next asset.</h2><p>Untuk strategic land, property development, investment partnership atau corporate enquiries, mari berdiskusi dengan ADTrans RealIndo.</p></div><a class="pc-btn" href="mailto:info@adtransrealindo.com">START A CONVERSATION →</a></section>
  </main><footer class="pc-footer"><span>© ${new Date().getFullYear()} ADTrans RealIndo</span><span>PROPERTY · CAPITAL · GOVERNANCE</span></footer></div>`;
}

window.addEventListener('hashchange',renderPortfolio);
if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',renderPortfolio); else renderPortfolio();
