const app = document.querySelector('#app');

const portfolioCSS = `
:root{--gold:#b89452;--ink:#101417;--paper:#f5f2eb;--muted:#687077;--line:#d8d3c8;--dark:#111820}
.public-corporate{font-family:Inter,Manrope,Arial,sans-serif;background:var(--paper);color:var(--ink);min-height:100vh}.public-corporate *{box-sizing:border-box}.public-corporate a{text-decoration:none;color:inherit}
.pc-nav{position:sticky;top:0;z-index:50;background:rgba(245,242,235,.95);backdrop-filter:blur(18px);border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;padding:18px clamp(20px,5vw,78px)}.pc-brand{display:flex;align-items:center;gap:11px;font-weight:900;letter-spacing:.1em}.pc-mark{width:42px;height:42px;border:1px solid var(--gold);display:grid;place-items:center;font-size:13px}.pc-brand small{display:block;font-size:9px;letter-spacing:.25em;color:#777;margin-top:3px}.pc-navlinks{display:flex;gap:25px;font-size:12px;font-weight:800}.pc-navlinks a:hover{color:#8e6d38}.pc-mobile{display:none;font-size:22px}
.pc-hero{min-height:730px;padding:90px clamp(20px,7vw,105px);display:grid;grid-template-columns:1.08fr .92fr;gap:50px;align-items:center;background:linear-gradient(120deg,#faf8f2,#e9e2d5);position:relative;overflow:hidden}.pc-hero:after{content:'';position:absolute;width:620px;height:620px;border:1px solid rgba(184,148,82,.25);border-radius:50%;right:-190px;top:-140px;box-shadow:0 0 0 70px rgba(184,148,82,.05),0 0 0 140px rgba(184,148,82,.025)}.pc-kicker,.pc-label{font-size:10px;letter-spacing:.28em;font-weight:900;color:#94733d}.pc-hero h1{font-size:clamp(48px,7vw,100px);line-height:.93;letter-spacing:-.055em;margin:20px 0;max-width:900px}.pc-hero h1 em,.pc-section h2 em{font-style:normal;color:#98763d}.pc-hero p{max-width:650px;color:#596066;font-size:17px;line-height:1.8}.pc-actions{display:flex;gap:12px;margin-top:32px;flex-wrap:wrap}.pc-btn{display:inline-block;padding:14px 21px;font-size:11px;font-weight:900;letter-spacing:.08em}.pc-btn.primary{background:#171c20;color:#fff}.pc-btn.outline{border:1px solid #a8a39a}.pc-hero-card{position:relative;z-index:2;margin-left:auto;width:min(430px,100%);background:#12181d;color:#fff;padding:38px;box-shadow:28px 28px 0 rgba(184,148,82,.18)}.pc-hero-card .big{font-size:70px;font-weight:900;color:var(--gold);line-height:1}.pc-hero-card h3{font-size:24px;margin:18px 0 10px}.pc-hero-card p{font-size:14px;color:#b3b9bc;line-height:1.7}
.pc-strip{background:#171c20;color:#fff;padding:23px clamp(20px,7vw,105px);display:grid;grid-template-columns:repeat(4,1fr);gap:20px}.pc-strip b{display:block;color:var(--gold);font-size:10px;letter-spacing:.15em;margin-bottom:6px}.pc-strip span{font-size:12px;color:#c5c9cb}.pc-section{padding:105px clamp(20px,7vw,105px)}.pc-section.dark{background:var(--dark);color:#fff}.pc-section-head{display:grid;grid-template-columns:.8fr 1.2fr;gap:45px;margin-bottom:50px}.pc-section h2{font-size:clamp(38px,5vw,68px);line-height:1;letter-spacing:-.04em;margin:0}.pc-copy{color:#697176;line-height:1.8;font-size:15px;max-width:680px}.dark .pc-copy{color:#aeb5b9}.pc-cards{display:grid;grid-template-columns:repeat(3,1fr);gap:1px;background:#cbc5b9}.pc-card{background:var(--paper);padding:35px;min-height:245px}.pc-card .num{font-size:11px;color:#9b783e;font-weight:900}.pc-card h3{font-size:24px;margin:52px 0 10px}.pc-card p{color:#6b7175;line-height:1.7;font-size:14px}.pc-list{border-top:1px solid #394149}.pc-list div{display:flex;gap:20px;padding:21px 0;border-bottom:1px solid #394149}.pc-list b{color:var(--gold);min-width:60px;font-size:11px}.pc-list span{color:#d3d7d9}.pc-projects{display:grid;grid-template-columns:1.25fr .75fr;gap:20px}.pc-project{min-height:320px;padding:34px;display:flex;flex-direction:column;justify-content:flex-end;background:linear-gradient(145deg,#2b343b,#111820);color:#fff;position:relative;overflow:hidden}.pc-project:before{content:'';position:absolute;inset:0;background:linear-gradient(135deg,transparent 45%,rgba(184,148,82,.2))}.pc-project>*{position:relative}.pc-project.small{min-height:150px}.pc-project h3{font-size:30px;margin:8px 0}.pc-project p{color:#c0c6c9;line-height:1.6}.pc-projects-side{display:grid;gap:20px}.pc-contact{background:#c8a96f;padding:78px clamp(20px,7vw,105px);display:flex;align-items:center;justify-content:space-between;gap:30px}.pc-contact h2{font-size:clamp(42px,6vw,76px);line-height:.95;margin:12px 0}.pc-contact p{max-width:620px;color:#403822;line-height:1.7}.pc-contact .pc-btn{background:#111820;color:#fff}.pc-footer{background:#0b0e10;color:#92999e;padding:32px clamp(20px,7vw,105px);display:flex;justify-content:space-between;font-size:10px;letter-spacing:.12em}
@media(max-width:850px){.pc-navlinks{display:none}.pc-mobile{display:block}.pc-hero{grid-template-columns:1fr;padding-top:70px}.pc-hero-card{margin:45px 0 0}.pc-strip{grid-template-columns:1fr 1fr}.pc-section-head,.pc-projects{grid-template-columns:1fr}.pc-cards{grid-template-columns:1fr}.pc-contact,.pc-footer{display:block}.pc-footer span{display:block;margin:8px 0}}
`;

function inject(){if(document.getElementById('pc-style'))return;const style=document.createElement('style');style.id='pc-style';style.textContent=portfolioCSS;document.head.appendChild(style)}

function renderPortfolio(){
  if((location.hash||'').toLowerCase()==='#imcs')return;
  inject();document.title='ADTrans RealIndo Corporate';
  app.innerHTML=`<div class="public-corporate">
  <header class="pc-nav"><a href="#home" class="pc-brand"><span class="pc-mark">AD</span><span>ADTRANS<small>REALINDO CORPORATE</small></span></a><nav class="pc-navlinks"><a href="#about">ABOUT</a><a href="#business">BUSINESS</a><a href="#projects">PORTFOLIO</a><a href="#governance">GOVERNANCE</a><a href="#contact">CONTACT</a></nav><span class="pc-mobile" aria-hidden="true">☰</span></header>
  <main>
   <section id="home" class="pc-hero"><div><div class="pc-kicker">ADTRANS REALINDO CORPORATE · COMPANY PORTFOLIO</div><h1>We create <em>real value</em> from strategic assets.</h1><p>ADTrans RealIndo adalah platform pengembangan properti dan investasi yang mengintegrasikan strategic land, development, capital partnership dan governance untuk membangun aset yang bernilai dan berkelanjutan.</p><div class="pc-actions"><a class="pc-btn primary" href="#projects">VIEW PORTFOLIO →</a><a class="pc-btn outline" href="#contact">PARTNER WITH US</a></div></div><div class="pc-hero-card"><div class="big">01</div><h3>Property. Capital. Governance.</h3><p>Our operating philosophy connects opportunity with disciplined execution, transparent decisions and measurable outcomes.</p></div></section>
   <section class="pc-strip"><div><b>01 · ASSETS</b><span>Strategic Land Intelligence</span></div><div><b>02 · DEVELOPMENT</b><span>Project & Delivery Control</span></div><div><b>03 · CAPITAL</b><span>Investment Partnerships</span></div><div><b>04 · GOVERNANCE</b><span>Evidence-based Management</span></div></section>
   <section id="about" class="pc-section"><div class="pc-section-head"><div class="pc-label">01 · ABOUT ADTRANS REALINDO CORPORATE</div><div><h2>Built to turn <em>opportunity</em> into enduring value.</h2><p class="pc-copy">Kami membangun ekosistem bisnis properti yang menghubungkan aset, modal, pengembangan dan pengendalian dalam satu kerangka kerja. Fokus kami adalah kualitas keputusan sebelum kualitas eksekusi.</p></div></div><div class="pc-cards"><article class="pc-card"><div class="num">01</div><h3>Strategic Assets</h3><p>Identifikasi, legal validation, valuation, zoning dan development potential sebagai fondasi keputusan.</p></article><article class="pc-card"><div class="num">02</div><h3>Development</h3><p>Feasibility, design, cost, schedule, procurement, construction dan delivery dalam satu control model.</p></article><article class="pc-card"><div class="num">03</div><h3>Capital</h3><p>Investment case yang transparan, risk-adjusted return dan partnership governance yang dapat dipertanggungjawabkan.</p></article></div></section>
   <section id="business" class="pc-section dark"><div class="pc-section-head"><div class="pc-label">02 · BUSINESS PLATFORM</div><div><h2>Four disciplines.<br><em>One operating model.</em></h2><p class="pc-copy">Setiap opportunity bergerak melalui tahapan validasi dan governance sebelum menjadi commitment.</p></div></div><div class="pc-list"><div><b>LAND</b><span>Land bank, legal due diligence, valuation, zoning & highest-best-use.</span></div><div><b>BUILD</b><span>Development feasibility, project controls, procurement & delivery.</span></div><div><b>CAPITAL</b><span>Investment structuring, financial modelling, partnership & funding.</span></div><div><b>CONTROL</b><span>Risk, contracts, approvals, KPI, audit trail & management alerts.</span></div></div></section>
   <section id="projects" class="pc-section"><div class="pc-section-head"><div class="pc-label">03 · PORTFOLIO</div><div><h2>Selected <em>opportunity</em> platforms.</h2><p class="pc-copy">Public portfolio menampilkan kategori dan kapabilitas. Detail project, financial data dan sensitive information tetap berada di dalam sistem internal perusahaan.</p></div></div><div class="pc-projects"><article class="pc-project"><div class="pc-label">STRATEGIC LAND</div><h3>Land & Asset Platform</h3><p>Strategic land opportunities with legal, market and development intelligence.</p></article><div class="pc-projects-side"><article class="pc-project small"><div class="pc-label">PROPERTY DEVELOPMENT</div><h3>Residential & Mixed Use</h3></article><article class="pc-project small"><div class="pc-label">INVESTMENT</div><h3>Capital Partnerships</h3></article></div></div></section>
   <section id="governance" class="pc-section dark"><div class="pc-section-head"><div><div class="pc-label">04 · GOVERNANCE</div><h2>Trust is built on <em>evidence.</em></h2><p class="pc-copy">ADTrans RealIndo menempatkan governance sebagai bagian dari operating system: data, approval, risk, contract dan accountability berjalan bersama.</p></div><div class="pc-list"><div><b>01</b><span>Validated data</span></div><div><b>02</b><span>Segregation of duties</span></div><div><b>03</b><span>Documented approvals</span></div><div><b>04</b><span>Continuous management control</span></div></div></div></section>
   <section id="contact" class="pc-contact"><div><div class="pc-label">05 · CONTACT</div><h2>Let's build<br>the next asset.</h2><p>Untuk strategic land, property development, investment partnership atau corporate enquiries, mari berdiskusi dengan ADTrans RealIndo.</p></div><a class="pc-btn" href="mailto:info@adtransrealindo.com">START A CONVERSATION →</a></section>
  </main><footer class="pc-footer"><span>© ${new Date().getFullYear()} ADTrans RealIndo Corporate</span><span>PROPERTY · CAPITAL · GOVERNANCE</span></footer></div>`;
}

window.addEventListener('hashchange',renderPortfolio);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',renderPortfolio);else renderPortfolio();
