import { createClient } from '@supabase/supabase-js';
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://nfvkdqpxexfymzuwdorx.supabase.co';
const SUPABASE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.VITE_SUPABASE_ANON_KEY || 'sb_publishable_4BG89zR_2gWWWeLqqDzALw_Atx9jAJ6';
const sb=createClient(SUPABASE_URL,SUPABASE_KEY);
const ORG='b68a13a7-15b2-47b1-9ce2-024da729e6a4';
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
const root=()=>document.querySelector('#content');
const style=`.workforce-view{display:grid;gap:16px}.wf-head,.wf-panel{padding:20px;border:1px solid var(--line,#e5e7eb);border-radius:16px;background:#fff}.wf-head h2{margin:6px 0}.wf-head p,.wf-muted{color:#697386;line-height:1.5}.wf-actions{display:flex;gap:8px;flex-wrap:wrap}.wf-btn{border:1px solid #cfd5cf;border-radius:10px;background:#fff;padding:9px 13px;cursor:pointer}.wf-btn.primary{background:#151b24;color:#fff;border-color:#151b24}.wf-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:10px}.wf-kpi{padding:15px;border:1px solid #e1e5e0;border-radius:13px}.wf-kpi strong{display:block;font-size:24px}.wf-kpi span{font-size:12px;color:#697386}.wf-table{width:100%;border-collapse:collapse;font-size:13px}.wf-table th,.wf-table td{text-align:left;padding:10px;border-bottom:1px solid #ecefec}.wf-status{font-size:11px;border-radius:999px;padding:4px 8px;background:#f0f2ef}.wf-msg{padding:10px;border-radius:10px;background:#fbfaf6;color:#4c5562}`;
if(!document.querySelector('#workforce-style')){const s=document.createElement('style');s.id='workforce-style';s.textContent=style;document.head.appendChild(s)}
async function load(){const [e,d,x]=await Promise.all([sb.from('employees').select('id,employee_no,full_name,job_title,status').eq('organization_id',ORG).order('full_name'),sb.from('employee_devices').select('id,employee_id,device_uid,status,last_seen_at').eq('organization_id',ORG),sb.from('attendance_events').select('id,employee_id,event_type,captured_at,verification_status,geofence_status').eq('organization_id',ORG).order('captured_at',{ascending:false}).limit(20)]);if(e.error)throw e.error;if(d.error)throw d.error;if(x.error)throw x.error;return {employees:e.data||[],devices:d.data||[],events:x.data||[]}}
async function render(){const h=root();if(!h)return;h.innerHTML='<div class="workforce-view"><section class="wf-head"><div class="eyebrow">WORKFORCE CONTROL</div><h2>Attendance & Field Workforce</h2><p>Attendance terhubung ke employee, device, proyek, lokasi, verifikasi, exception dan payroll. Sistem menggunakan server timestamp dan client-event id untuk mengurangi duplikasi/replay.</p><div class="wf-actions"><button class="wf-btn primary" id="wf-clock">Clock-in perangkat ini</button><button class="wf-btn" id="wf-refresh">Refresh</button></div></section><section id="wf-data" class="wf-panel"><span class="wf-muted">Loading…</span></section></div>';try{const d=await load();const active=d.employees.filter(e=>e.status==='ACTIVE').length;const verified=d.events.filter(e=>e.verification_status==='VERIFIED').length;const open=d.events.filter(e=>e.verification_status==='EXCEPTION').length;document.querySelector('#wf-data').innerHTML=`<div class="wf-grid"><div class="wf-kpi"><strong>${active}</strong><span>Active employees</span></div><div class="wf-kpi"><strong>${d.devices.length}</strong><span>Registered devices</span></div><div class="wf-kpi"><strong>${verified}</strong><span>Verified recent events</span></div><div class="wf-kpi"><strong>${open}</strong><span>Exceptions in recent events</span></div></div><div style="margin-top:18px;overflow:auto"><table class="wf-table"><thead><tr><th>Waktu</th><th>Employee</th><th>Event</th><th>Verification</th><th>Geofence</th></tr></thead><tbody>${d.events.map(x=>{const e=d.employees.find(a=>a.id===x.employee_id);return `<tr><td>${esc(new Date(x.captured_at).toLocaleString('id-ID'))}</td><td>${esc(e?.full_name||x.employee_id)}</td><td>${esc(x.event_type)}</td><td><span class="wf-status">${esc(x.verification_status)}</span></td><td>${esc(x.geofence_status||'UNKNOWN')}</td></tr>`}).join('')||'<tr><td colspan="5">Belum ada event attendance.</td></tr>'}</tbody></table></div>`;document.querySelector('#wf-refresh').onclick=render;document.querySelector('#wf-clock').onclick=clockIn}catch(e){document.querySelector('#wf-data').innerHTML=`<div class="wf-msg">Workforce gagal dimuat: ${esc(e.message)}</div>`}}
async function clockIn(){const {data:{user}}=await sb.auth.getUser();if(!user){alert('Silakan login terlebih dahulu.');return}const {data:emp}=await sb.from('employees').select('id').eq('organization_id',ORG).eq('profile_id',user.id).eq('status','ACTIVE').maybeSingle();if(!emp){alert('Employee profile aktif untuk akun ini belum tersedia.');return}const deviceUid=localStorage.getItem('adtrans-device-uid')||crypto.randomUUID();localStorage.setItem('adtrans-device-uid',deviceUid);const p={p_employee_id:emp.id,p_event_type:'CLOCK_IN',p_client_event_id:`${deviceUid}-${Date.now()}`,p_device_uid:deviceUid,p_verification_method:'DEVICE',p_evidence:{source:'imcs-workforce',client_time:new Date().toISOString()}};const {error}=await sb.rpc('record_attendance_event',p);if(error){alert(`Clock-in belum dapat dicatat: ${error.message}`);return}alert('Clock-in tercatat dan menunggu verifikasi sesuai kebijakan.');render()}
function inject(){const nav=document.querySelector('aside nav');if(!nav||nav.querySelector('[data-page="Attendance & Workforce"]'))return;const b=document.createElement('button');b.className='nav';b.dataset.page='Attendance & Workforce';b.innerHTML='<span>◷</span>Attendance & Workforce';b.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');const t=document.querySelector('#page-title');if(t)t.textContent='Attendance & Workforce';render()};nav.insertBefore(b,nav.children[2]||null)}
const ob=new MutationObserver(inject);ob.observe(document.body,{childList:true,subtree:true});inject();
